# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: {{.Release.Namespace}}
data:
  config: |
    {{- if .Values.workflowDefaults }}
    workflowDefaults:
    {{- toYaml .Values.workflowDefaults | nindent 6 }}
    {{- end }}
    mainContainer:
      securityContext: {{- toYaml .Values.argo.mainContainer.securityContext | nindent 8 }}
    executor:
      securityContext: {{- toYaml .Values.argo.executor.securityContext | nindent 8 }}
      resources:
        requests:
          cpu: {{ .Values.argo.executor.waitContainerResources.requests.cpu }}
          memory: {{ .Values.argo.executor.waitContainerResources.requests.memory }}
        limits:
          cpu: {{ .Values.argo.executor.waitContainerResources.limits.cpu }}
          memory: {{ .Values.argo.executor.waitContainerResources.limits.memory }}
    {{ if .Values.argo.logging }}
    links:
    {{- if .Values.argo.logging.grafana }}
    {{-  include "getDefaultLoggingUrl" . | nindent 4 }}
    {{- end }}
    {{- if .Values.argo.logging.additionalLinks }}
    {{- range .Values.argo.logging.additionalLinks }}
    - name: {{ .name }}
      scope: {{ .scope }}
      url: {{ .url }}
    {{- end }}
    {{- end }}
    {{- end }}
    artifactRepository:
      archiveLogs: true
      s3:
        bucket: {{ required "Missing an entry for .Values.global.s3Configuration.bucketName!" .Values.global.s3Configuration.bucketName }}
        keyPrefix: {{ .Values.objectStorage.keyPrefix }}
        endpoint: "{{ required "Missing an entry for .Values.global.s3Configuration.server.endpoint!" .Values.global.s3Configuration.server.endpoint }}"        #AWS => s3.amazonaws.com; GCS => storage.googleapis.com
        insecure: {{ not .Values.global.s3Configuration.server.ssl }}                  #omit for S3/GCS. Needed when minio runs without TLS
        accessKeySecret:                #omit if accessing via AWS IAM
          name: {{.Values.objectStorage.secret.name}}
          key: accessKey
        secretKeySecret:                #omit if accessing via AWS IAM
          name: {{.Values.objectStorage.secret.name}}
          key: secretKey
    persistence:

    metricsConfig:
      enabled: true # fixed in 2.4.2
      path: /metrics
      port: 9090