apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.objectStorage.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "defaultLabels" . | nindent 4 }}
type: Opaque
stringData:
  accessKey: {{ required "Missing an entry for .Values.global.s3Configuration.accessKey!" .Values.global.s3Configuration.accessKey }}
  secretKey: {{ required "Missing an entry for .Values.global.s3Configuration.accessKey!" .Values.global.s3Configuration.secretKey }}
