{{ if .Values.targetKubeconfig }}
apiVersion: v1
kind: Secret
metadata:
  name: gardener-resource-manager-target-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-resource-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  kubeconfig.yaml: {{ .Values.targetKubeconfig | b64enc }}
{{- end }}
