apiVersion: v1
kind: ServiceAccount
metadata:
  name: gardener-resource-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-resource-manager
    helm.sh/chart: gardener-resource-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
