apiVersion: v1
kind: Service
metadata:
  name: gardener-resource-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-resource-manager
    helm.sh/chart: gardener-resource-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.metricsPort }}
    protocol: TCP
  - name: health
    port: {{ .Values.healthPort }}
    protocol: TCP
  selector:
    app.kubernetes.io/name: gardener-resource-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
