
---
{{ if .Values.minio.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    annotations:
        {{- range $key, $value := .Values.minio.ingress.annotations }}
        {{ $key }}: {{ $value }}
        {{- end }}
    labels:
        garden.sapcloud.io/purpose: managed-cert
        {{- range $key, $value := .Values.minio.ingress.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    name: {{ .Values.minio.ingress.name }}
    namespace: {{ .Release.Namespace }}
spec:
    rules:
    - host: {{ .Values.minio.ingress.host }}
      http:
          paths:
          - backend:
                serviceName: {{ .Values.minio.service.name }}
                servicePort: {{.Values.minio.service.port}}
            path: /
    tls:
    - hosts:
      - {{ .Values.minio.ingress.host }}
      secretName: minio-ingress-tls
{{ end }}