#! /bin/bash
#
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

have_value=$(printenv $ENV_NAME)
want_value=$ENV_VALUE

if [[ "$have_value" != "$want_value" ]]; then
    echo "$ENV_NAME is $have_value not $want_value"
    exit 1
fi