#! /bin/bash
#
# SPDX-FileCopyrightText: Copyright Contributors to the Gardener project
#
# SPDX-License-Identifier: Apache-2.0

if [[ $TEST_NAME != "test" ]]; then
    echo "TESTNAME is $TEST_NAME"
    exit 1
fi