#! /bin/bash
#
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

if [[ ! -f $FILE ]]; then
    echo "File $FILE does not exist"
    exit 1
fi


if [[ $(< $FILE) != "test" ]]; then
    echo "File $FILE content does not match"
    exit 1
fi