#! /bin/bash
#
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

if [[ -f $FILE ]]; then
    echo "File $FILE exists"
    exit 1
fi
