#! /bin/bash
#
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

if [[ $TEST_NAME != "test" ]]; then
    echo "TESTNAME is $TEST_NAME"
    exit 1
fi