# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0
enabled: true

images:
  reserve-excess-capacity: gcr.io/google_containers/pause-amd64:3.1


replicas: 5 # each replica reserves 1 CPU and 1GB memory

resources:
  requests:
    cpu: 1000m
    memory: 1000Mi
  limits:
    cpu: 1000m
    memory: 1000Mi