// +build !ignore_autogenerated

/*
Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package openapi

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.ConfigElement":                    schema_pkg_apis_testmachinery_v1beta1_ConfigElement(ref),
		"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.ConfigSource":                     schema_pkg_apis_testmachinery_v1beta1_ConfigSource(ref),
		"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestDefMetadata":                  schema_pkg_apis_testmachinery_v1beta1_TestDefMetadata(ref),
		"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestDefSpec":                      schema_pkg_apis_testmachinery_v1beta1_TestDefSpec(ref),
		"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestDefinition":                   schema_pkg_apis_testmachinery_v1beta1_TestDefinition(ref),
		"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestLocation":                     schema_pkg_apis_testmachinery_v1beta1_TestLocation(ref),
		"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestflowStep":                     schema_pkg_apis_testmachinery_v1beta1_TestflowStep(ref),
		"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestflowStepStatus":               schema_pkg_apis_testmachinery_v1beta1_TestflowStepStatus(ref),
		"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestflowStepStatusTestDefinition": schema_pkg_apis_testmachinery_v1beta1_TestflowStepStatusTestDefinition(ref),
		"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.Testrun":                          schema_pkg_apis_testmachinery_v1beta1_Testrun(ref),
		"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestrunKubeconfigs":               schema_pkg_apis_testmachinery_v1beta1_TestrunKubeconfigs(ref),
		"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestrunList":                      schema_pkg_apis_testmachinery_v1beta1_TestrunList(ref),
		"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestrunSpec":                      schema_pkg_apis_testmachinery_v1beta1_TestrunSpec(ref),
		"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestrunStatus":                    schema_pkg_apis_testmachinery_v1beta1_TestrunStatus(ref),
	}
}

func schema_pkg_apis_testmachinery_v1beta1_ConfigElement(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ConfigElement is a parameter of a certain type which is passed to TestDefinitions.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"type": {
						SchemaProps: spec.SchemaProps{
							Description: "Type of the config value. For now only environament varibales are supported.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"name": {
						SchemaProps: spec.SchemaProps{
							Description: "Name of the environment variable. Must be a C_IDENTIFIER.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"value": {
						SchemaProps: spec.SchemaProps{
							Description: "value of the environament variable.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"valueFrom": {
						SchemaProps: spec.SchemaProps{
							Description: "Fetches the value from a secret or configmap on the testmachinery cluster.",
							Ref:         ref("github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.ConfigSource"),
						},
					},
					"path": {
						SchemaProps: spec.SchemaProps{
							Description: "Only for type=file. Path where the file should be mounted.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
				Required: []string{"type", "name", "value"},
			},
		},
		Dependencies: []string{
			"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.ConfigSource"},
	}
}

func schema_pkg_apis_testmachinery_v1beta1_ConfigSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ConfigSource represents a source for the value of a config element.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"configMapKeyRef": {
						SchemaProps: spec.SchemaProps{
							Description: "Selects a key of a ConfigMap.",
							Ref:         ref("k8s.io/api/core/v1.ConfigMapKeySelector"),
						},
					},
					"secretKeyRef": {
						SchemaProps: spec.SchemaProps{
							Description: "Selects a key of a secret in the pod's namespace",
							Ref:         ref("k8s.io/api/core/v1.SecretKeySelector"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"k8s.io/api/core/v1.ConfigMapKeySelector", "k8s.io/api/core/v1.SecretKeySelector"},
	}
}

func schema_pkg_apis_testmachinery_v1beta1_TestDefMetadata(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TestDefMetadata holds the metadata of a testrun.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"name": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"name"},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_testmachinery_v1beta1_TestDefSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TestDefSpec is the actual description of the test.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"owner": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"recipientsOnFailure": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
					"description": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"labels": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
					"behavior": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
					"activeDeadlineSeconds": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int64",
						},
					},
					"command": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
					"args": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
					"image": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"config": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.ConfigElement"),
									},
								},
							},
						},
					},
				},
				Required: []string{"owner", "recipientsOnFailure", "description", "labels", "behavior", "activeDeadlineSeconds", "command", "args", "image"},
			},
		},
		Dependencies: []string{
			"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.ConfigElement"},
	}
}

func schema_pkg_apis_testmachinery_v1beta1_TestDefinition(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TestDefinition describes the execution of a test.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestDefMetadata"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestDefSpec"),
						},
					},
				},
				Required: []string{"kind", "spec"},
			},
		},
		Dependencies: []string{
			"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestDefMetadata", "github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestDefSpec"},
	}
}

func schema_pkg_apis_testmachinery_v1beta1_TestLocation(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TestLocation describes a location to search for TestDefinitions.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"type": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"repo": {
						SchemaProps: spec.SchemaProps{
							Description: "Only for LocationType git",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"revision": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"hostPath": {
						SchemaProps: spec.SchemaProps{
							Description: "The absolute host on the minikube VM. Only for local",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
				Required: []string{"type"},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_testmachinery_v1beta1_TestflowStep(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TestflowStep is a reference to one or more TestDefinitions to execute in a series of steps.TestflowStep TestDefinitions can be either defined by a Name or a Label.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"name": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"label": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"condition": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"config": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.ConfigElement"),
									},
								},
							},
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.ConfigElement"},
	}
}

func schema_pkg_apis_testmachinery_v1beta1_TestflowStepStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TestflowStepStatus is the status of Testflow step",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"testdefinition": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestflowStepStatusTestDefinition"),
						},
					},
					"phase": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"startTime": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.Time"),
						},
					},
					"completionTime": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.Time"),
						},
					},
					"duration": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int64",
						},
					},
					"exportArtifactKey": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"exportArtifactKey"},
			},
		},
		Dependencies: []string{
			"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestflowStepStatusTestDefinition", "k8s.io/apimachinery/pkg/apis/meta/v1.Time"},
	}
}

func schema_pkg_apis_testmachinery_v1beta1_TestflowStepStatusTestDefinition(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TestflowStepStatusTestDefinition holds information about the used testdefinition and its location.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"name": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"location": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestLocation"),
						},
					},
					"owner": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"recipientsOnFailure": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
					"activeDeadlineSeconds": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int64",
						},
					},
					"position": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"object"},
							AdditionalProperties: &spec.SchemaOrBool{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
				},
				Required: []string{"recipientsOnFailure", "activeDeadlineSeconds", "position"},
			},
		},
		Dependencies: []string{
			"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestLocation"},
	}
}

func schema_pkg_apis_testmachinery_v1beta1_Testrun(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Testrun is the description of the testflow that should be executed.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestrunSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestrunStatus"),
						},
					},
				},
				Required: []string{"spec", "status"},
			},
		},
		Dependencies: []string{
			"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestrunSpec", "github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestrunStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_testmachinery_v1beta1_TestrunKubeconfigs(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TestrunKubeconfigs are parameters where Shoot, Seed or a Gardener kubeconfig for the Testrun can be specified.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"gardener": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"seed": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"shoot": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_testmachinery_v1beta1_TestrunList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TestrunList contains a list of Testruns",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ListMeta"),
						},
					},
					"items": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.Testrun"),
									},
								},
							},
						},
					},
				},
				Required: []string{"items"},
			},
		},
		Dependencies: []string{
			"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.Testrun", "k8s.io/apimachinery/pkg/apis/meta/v1.ListMeta"},
	}
}

func schema_pkg_apis_testmachinery_v1beta1_TestrunSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TestrunSpec is the specification of a Testrun.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"creator": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"ttlSecondsAfterFinished": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int32",
						},
					},
					"testLocations": {
						SchemaProps: spec.SchemaProps{
							Description: "TestLocation define repositories to look for TestDefinitions that then executed in a workkflow as specified in testflow.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestLocation"),
									},
								},
							},
						},
					},
					"kubeconfigs": {
						SchemaProps: spec.SchemaProps{
							Description: "Base64 encoded kubeconfigs that are mounted to every testflow step. They are available at $TM_KUBECONFIG_PATH/xxx.config, where xxx is either (gardener, seed or shoot).",
							Ref:         ref("github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestrunKubeconfigs"),
						},
					},
					"config": {
						SchemaProps: spec.SchemaProps{
							Description: "Global config which is available to all tests in the testflow and onExit flow.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.ConfigElement"),
									},
								},
							},
						},
					},
					"testFlow": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type: []string{"array"},
										Items: &spec.SchemaOrArray{
											Schema: &spec.Schema{
												SchemaProps: spec.SchemaProps{
													Ref: ref("github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestflowStep"),
												},
											},
										},
									},
								},
							},
						},
					},
					"onExit": {
						SchemaProps: spec.SchemaProps{
							Description: "OnExit flow is called when the test is completed.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type: []string{"array"},
										Items: &spec.SchemaOrArray{
											Schema: &spec.Schema{
												SchemaProps: spec.SchemaProps{
													Ref: ref("github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestflowStep"),
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.ConfigElement", "github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestLocation", "github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestflowStep", "github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestrunKubeconfigs"},
	}
}

func schema_pkg_apis_testmachinery_v1beta1_TestrunStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TestrunStatus is the status of the Testrun.",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"phase": {
						SchemaProps: spec.SchemaProps{
							Description: "Phase is the summary of all executed steps.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"state": {
						SchemaProps: spec.SchemaProps{
							Description: "State is a string that represents the actual state and/or process of the testrun.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"startTime": {
						SchemaProps: spec.SchemaProps{
							Description: "StartTime is the time when the argo workflow starts executing the steps.",
							Ref:         ref("k8s.io/apimachinery/pkg/apis/meta/v1.Time"),
						},
					},
					"completionTime": {
						SchemaProps: spec.SchemaProps{
							Description: "CompletionTime is the time when the argo workflow is completed.",
							Ref:         ref("k8s.io/apimachinery/pkg/apis/meta/v1.Time"),
						},
					},
					"duration": {
						SchemaProps: spec.SchemaProps{
							Description: "Duration represents the overall duration of the argo workflow. This value is calculated by (CompletionTime - StartTime)",
							Type:        []string{"integer"},
							Format:      "int64",
						},
					},
					"workflow": {
						SchemaProps: spec.SchemaProps{
							Description: "Workflow is the name of the generated argo workflow",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"steps": {
						SchemaProps: spec.SchemaProps{
							Description: "Steps is the detailed summary of every step. It also shows all specific executed tests.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type: []string{"array"},
										Items: &spec.SchemaOrArray{
											Schema: &spec.Schema{
												SchemaProps: spec.SchemaProps{
													Ref: ref("github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestflowStepStatus"),
												},
											},
										},
									},
								},
							},
						},
					},
					"ingested": {
						SchemaProps: spec.SchemaProps{
							Description: "Ingested states whether the result of a testrun is already ingested into a persistant storage (db).",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
				},
				Required: []string{"ingested"},
			},
		},
		Dependencies: []string{
			"github.com/gardener/test-infra/pkg/apis/testmachinery/v1beta1.TestflowStepStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.Time"},
	}
}
