
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: shootsmeasurement.telemetry.testmachinery.gardener.cloud
spec:
  group: telemetry.testmachinery.gardener.cloud
  versions:
  - name: v1beta1
    served: true
    storage: true
  version: v1beta1
  scope: Namespaced
  names:
    kind: ShootsMeasurement
    plural: shootsmeasurement
    shortNames:
    - sm
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Phase
    type: string
    description: The phase indicates the current status of the overall measurement.
    JSONPath: .status.phase
  - name: Message
    type: string
    description: Optional message for detailed description of the actual state
    JSONPath: .status.message