# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

controller:
  enableLeaderElection: false
  maxConcurrentSyncs: 5
  webhook:
    port: 443
    certDir: ""

testmachinery:
  testdefPath: test/.test-defs
  local: false
  insecure: false
  disableCollector: true
  cleanWorkflowPods: false

  github:
    cache:
      cacheDir: /tmp/tm/cache
      cacheDiskSizeGB: 5
      maxAgeSeconds: 60
  argo:
    argoUI:
      ingress:
        enabled: false
        host: argoui.example.com

  s3Configuration:
    server:
      minio:
        distributed: false
        ingress:
          enabled: true
          host: minio.ingress.tm-it.core.shoot.canary.k8s-hana.ondemand.com
      ssl: false
    bucketName: testmachinery
    accessKey: foo
    secretKey: bar

#  esConfiguration:
#    endpoint: https:...:9200
#    username: user
#    password: my-password

# imageVectorOverwrite: |
#  - name: argo-ui
#    sourceRepository: github.com/argoproj/argo
#    repository: argoproj/argocli
#    tag: "v2.6.3"
#  - name: argo-workflow-controller
#    sourceRepository: github.com/argoproj/argo
#    repository: argoproj/workflow-controller
#    tag: "v2.6.3"
#  - name: argo-executor
#    sourceRepository: github.com/argoproj/argo
#    repository: argoproj/argoexec
#    tag: "v2.6.3"
#  - name: minio
#    sourceRepository: github.com/minio/minio
#    repository: minio/minio
#    tag: "RELEASE.2020-04-04T05-39-31Z"