#!/usr/bin/env bash
#

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

printf "\nIntegration tests\n"

if [[ -z "${SOURCE_PATH}" ]]; then
  export SOURCE_PATH="$(readlink -f "$(dirname ${0})/..")"
else
  export SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi

VERSION_PATH="$(readlink -f "${VERSION_PATH}")"

VERSION="$(cat $VERSION_PATH/version)"
GIT_COMMIT_SHA="$(GIT_DIR=$SOURCE_PATH/.git git rev-parse @)"
NAMESPACE=default

# Install Kubectl
K8S_VERSION=1.30.5
curl -LO https://dl.k8s.io/release/v${K8S_VERSION}/bin/linux/amd64/kubectl
chmod +x ./kubectl
mv ./kubectl /usr/local/bin/kubectl

# Install Helm (see https://docs.helm.sh/using_helm/#from-script).
if ! which helm 1>/dev/null; then
  echo -n "Installing helm... "
  curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
  chmod 700 ./get_helm.sh
  bash ./get_helm.sh
  rm ./get_helm.sh
  echo "done."
fi


# Install Ginkgo (test framework) to be able to execute the tests.
cd "${SOURCE_PATH}"
go install -mod=mod github.com/onsi/ginkgo/ginkgo


# Download Testmachinery Kubeconfig
TM_KUBECONFIG=/tm/kubeconfig
mkdir -p /tm
/cc/utils/cli.py config attribute --cfg-type kubernetes --cfg-name testmachinery-it --key kubeconfig > $TM_KUBECONFIG

export S3_ENDPOINT="minio.ingress.tm-it.core.shoot.canary.k8s-hana.ondemand.com"

echo "Testmachinery version: $VERSION"

###################
# Generate charts #
###################
make -C $SOURCE_PATH gen-certs
ca_bundle="$(cat $SOURCE_PATH/assets/ca.crt)"
crt="$(cat $SOURCE_PATH/assets/tls.crt)"
key="$(cat $SOURCE_PATH/assets/tls.key)"

github_config=$($SOURCE_PATH/.ci/scripts/gh_config.py | base64 -w 0)

controller_chart="$(helm template --namespace ${NAMESPACE} \
  --set "testmachinery.github.credentials=${github_config}" \
  --set "controller.verbosity=5,controller.tag=${VERSION}" \
  --set "controller.tls.caBundle=${ca_bundle},controller.tls.crt=${crt},controller.tls.key=${key}" \
  -f $SOURCE_PATH/.ci/integrationtest-config.yaml $SOURCE_PATH/charts/testmachinery)"


################################
# clean previous installation  #
################################
set +e
# remove zombies
for ns in $(kubectl --kubeconfig=$TM_KUBECONFIG get ns --no-headers | awk '{ print $1 }'); do
  echo "Cleanup $ns"
  kubectl --kubeconfig=$TM_KUBECONFIG -n $ns delete tr --all --wait=false
  kubectl --kubeconfig=$TM_KUBECONFIG -n $ns delete wf --all --wait=false
  # give the tm some time to delete tr's correctly
  sleep 20

  kubectl --kubeconfig=$TM_KUBECONFIG -n $ns get tr -oname | xargs kubectl --kubeconfig=$TM_KUBECONFIG -n $ns patch -p '{"metadata":{"finalizers":[]}}' --type=merge
  kubectl --kubeconfig=$TM_KUBECONFIG -n $ns get wf -oname | xargs kubectl --kubeconfig=$TM_KUBECONFIG -n $ns patch -p '{"metadata":{"finalizers":[]}}' --type=merge

  if [[ $ns == tm-it* ]]; then
    kubectl --kubeconfig=$TM_KUBECONFIG delete ns $ns
  fi
done

echo "> Delete leaked managed resrources"
kubectl --kubeconfig=$TM_KUBECONFIG -n $NAMESPACE scale --replicas=0 deploy testmachinery-controller
kubectl --kubeconfig=$TM_KUBECONFIG -n $NAMESPACE delete managedresources --all
kubectl --kubeconfig=$TM_KUBECONFIG -n $NAMESPACE wait --for=delete managedresources --all
echo "> Delete leaked volumes"
kubectl --kubeconfig=$TM_KUBECONFIG -n $NAMESPACE delete pvc --all
echo "> Delete previous tm installation"
echo "$controller_chart" | kubectl --kubeconfig=$TM_KUBECONFIG delete -f -
set -e

############################################################################
# installation of prerequisites, controller, validation webhooks and roles #
############################################################################
# install controller, validation webhook and roles
echo "$controller_chart" | kubectl --kubeconfig=$TM_KUBECONFIG create -f -

# run integration tests with ginkgo

ginkgo -mod=mod --slowSpecThreshold=30 -p --nodes=5 ./test/validationwebhook -- --tm-namespace=${NAMESPACE} --kubecfg=${TM_KUBECONFIG} --git-commit-sha=${GIT_COMMIT_SHA}
ginkgo -mod=mod --slowSpecThreshold=600 -r -p --nodes=5 ./test/controller -- --tm-namespace=${NAMESPACE} --kubecfg=${TM_KUBECONFIG} --git-commit-sha=${GIT_COMMIT_SHA}
ginkgo -mod=mod --slowSpecThreshold=600 -p --nodes=5 ./test/testrunner/... -- --tm-namespace=${NAMESPACE} --kubecfg=${TM_KUBECONFIG} --git-commit-sha=${GIT_COMMIT_SHA}

#######################
# clean installation  #
#######################
# wait for controller to clean up all testruns.
sleep 30

echo "> Delete leaked managed resources"
kubectl --kubeconfig=$TM_KUBECONFIG -n $NAMESPACE scale --replicas=0 deploy testmachinery-controller
kubectl --kubeconfig=$TM_KUBECONFIG -n $NAMESPACE delete managedresources --all
echo "> Delete leaked volumes"
kubectl --kubeconfig=$TM_KUBECONFIG -n $NAMESPACE delete pvc --all
echo "> Delete previous tm installation"
echo "$controller_chart" | kubectl --kubeconfig=$TM_KUBECONFIG delete -f -