#!/usr/bin/env bash
#
# Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -e
export GO111MODULE=on

printf "\nIntegration tests tm-bot\n"

if [[ -z "${SOURCE_PATH}" ]]; then
  export SOURCE_PATH="$(readlink -f "$(dirname ${0})/..")"
else
  export SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi

VERSION_PATH="$(readlink -f "${VERSION_PATH}")"

TESTMACHINERY_CONFIG_NAME="testmachinery-it"
VERSION="$(cat $VERSION_PATH/version)"
GIT_COMMIT_SHA="$(GIT_DIR=$SOURCE_PATH/.git git rev-parse @)"
NAMESPACE=tm-bot

# Install Kubectl
curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.13.4/bin/linux/amd64/kubectl
chmod +x ./kubectl
mv ./kubectl /usr/local/bin/kubectl

# Install Helm (see https://docs.helm.sh/using_helm/#from-script).
if ! which helm 1>/dev/null; then
  echo -n "Installing helm... "
  install_helm_path="./get_helm.sh"
  curl https://raw.githubusercontent.com/helm/helm/v2.13.0/scripts/get > "${install_helm_path}"
  chmod 700 "${install_helm_path}"
  export DESIRED_VERSION=v2.13.0
  bash "${install_helm_path}"
  rm ./"${install_helm_path}"
  echo "done."
fi


# Install Ginkgo (test framework) to be able to execute the tests.
cd "${SOURCE_PATH}"
go install -mod=vendor ./vendor/github.com/onsi/ginkgo/ginkgo


# Download Testmachinery Kubeconfig
TM_KUBECONFIG=/tm/kubeconfig
mkdir -p /tm
/cc/utils/cli.py config attribute --cfg-type kubernetes --cfg-name testmachinery-it --key kubeconfig > $TM_KUBECONFIG


echo "Testmachinery version: $VERSION"

###################
# Generate charts #
###################
make -C $SOURCE_PATH gen-certs
ca_bundle="$(cat $SOURCE_PATH/assets/ca.crt)"
crt="$(cat $SOURCE_PATH/assets/tls.crt)"
key="$(cat $SOURCE_PATH/assets/tls.key)"

GITHUB_APP_ID="$(/cc/utils/cli.py config attribute --cfg-type testmachinery --cfg-name $TESTMACHINERY_CONFIG_NAME --key bot.github.appID | base64 -w0)"
GITHUB_KEY="$(/cc/utils/cli.py config attribute --cfg-type testmachinery --cfg-name $TESTMACHINERY_CONFIG_NAME --key bot.github.key | base64 -w0)"
GITHUB_WEBHOOK_SECRET_TOKEN="$(/cc/utils/cli.py config attribute --cfg-type testmachinery --cfg-name $TESTMACHINERY_CONFIG_NAME --key bot.github.webhookSecretToken | tr -d '\n' | base64 -w0)"
GITHUB_WEBHOOK_URL="$(/cc/utils/cli.py config attribute --cfg-type testmachinery --cfg-name $TESTMACHINERY_CONFIG_NAME --key bot.github.webhookUrl)"

github_config=$($SOURCE_PATH/.ci/scripts/gh_config.py | base64 -w 0)
pull_secrets_value_file_path="$SOURCE_PATH/.ci/pull_secrets.yaml"
$SOURCE_PATH/.ci/scripts/pull_secrets.py > $pull_secrets_value_file_path


bot_chart="$(helm template --namespace ${NAMESPACE} \
  --set "secrets.github.appID=${GITHUB_APP_ID},secrets.github.key=${GITHUB_KEY},secrets.github.webhookSecretToken=${GITHUB_WEBHOOK_SECRET_TOKEN},ingress.host=${GITHUB_WEBHOOK_URL},bot.verbosity=5,bot.tag=${VERSION},bot.tls.caBundle=${ca_bundle},bot.tls.crt=${crt},bot.tls.key=${key}" $SOURCE_PATH/charts/tm-bot)"


################################
# clean previous installation  #
################################
set +e
echo "$bot_chart" | kubectl --kubeconfig=$TM_KUBECONFIG delete -f -
set -e

############################################################################
# installation of bot, ingress and roles #
############################################################################
# install bot, validation webhook and roles
echo "$bot_chart" | kubectl --kubeconfig=$TM_KUBECONFIG create -f -

# run integration tests with ginkgo
# tbd

#######################
# clean installation  #
#######################
echo "$bot_chart" | kubectl --kubeconfig=$TM_KUBECONFIG delete -f -
