#!/usr/bin/env bash
#

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

if [[ -z "${SOURCE_PATH}" ]]; then
  export SOURCE_PATH="$(readlink -f "$(dirname ${0})/..")"
else
  export SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi

cd "${SOURCE_PATH}"

# Download kubernetes binaries
K8S_VERSION=1.31.3
ETCD_VER=v3.4.34

mkdir -p /usr/local/kubebuilder/bin
curl -LO https://dl.k8s.io/release/v${K8S_VERSION}/bin/linux/amd64/kubectl
chmod +x kubectl
mv kubectl /usr/local/kubebuilder/bin/kubectl

curl -LO https://dl.k8s.io/release/v${K8S_VERSION}/bin/linux/amd64/kube-apiserver
chmod +x kube-apiserver
mv kube-apiserver /usr/local/kubebuilder/bin/kube-apiserver

curl -L https://storage.googleapis.com/etcd/${ETCD_VER}/etcd-${ETCD_VER}-linux-amd64.tar.gz -o /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
tar xzvf /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz  etcd-${ETCD_VER}-linux-amd64/etcd
mv etcd-${ETCD_VER}-linux-amd64/etcd /usr/local/kubebuilder/bin/etcd

go test ./cmd/... ./pkg/...