#!/bin/bash
#
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

PROJECT_ROOT="$(dirname $0)/.."
export PROJECT_ROOT

# setup virtual GOPATH
export REPO_ROOT=${REPO_ROOT}
source "${GARDENER_HACK_DIR}"/vgopath-setup.sh

CODE_GEN_DIR=$(go list -m -f '{{.Dir}}' k8s.io/code-generator)
source "${CODE_GEN_DIR}/kube_codegen.sh"

rm -f ${GOPATH}/bin/*-gen

echo "> Generating internal groups for TestMachinery"

kube::codegen::gen_helpers \
  --boilerplate "${PROJECT_ROOT}/hack/boilerplate.go.txt" \
  "${PROJECT_ROOT}/pkg/apis"

kube::codegen::gen_helpers \
  --boilerplate "${PROJECT_ROOT}/hack/boilerplate.go.txt" \
  "${PROJECT_ROOT}/pkg/util/strconf"

echo "Generating openapi definitions"
kube::codegen::gen_openapi \
    --boilerplate "${PROJECT_ROOT}/hack/boilerplate.go.txt" \
    --output-dir "${PROJECT_ROOT}/pkg/openapi" \
    --output-pkg "github.com/gardener/test-infra/pkg/openapi" \
    --report-filename "${PROJECT_ROOT}/pkg/openapi/api_violations.report" \
    --update-report \
    "${PROJECT_ROOT}/pkg"