#!/bin/bash
#
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

PROJECT_ROOT="github.com/gardener/test-infra"

echo "Generating internal groups for $PROJECT_ROOT"
$(dirname $0)/../vendor/k8s.io/code-generator/generate-internal-groups.sh \
  all \
  $PROJECT_ROOT/pkg/client/testmachinery \
  $PROJECT_ROOT/pkg/apis \
  $PROJECT_ROOT/pkg/apis \
  testmachinery:v1beta1 \
  -h $(dirname $0)/boilerplate.go.txt

go install ./$(dirname "${0}")/../vendor/k8s.io/kube-openapi/cmd/openapi-gen

echo "Generating openapi definitions"
${GOPATH}/bin/openapi-gen "$@" \
  --v 1 \
  --logtostderr \
  --input-dirs=$PROJECT_ROOT/pkg/apis/testmachinery/v1beta1 \
  --report-filename=./$(dirname "${0}")/../pkg/openapi/api_violations.report \
  --output-package=$PROJECT_ROOT/pkg/openapi \
  -h $(dirname $0)/boilerplate.go.txt

# echo "Generating groups for $PROJECT_ROOT"
# $(dirname $0)/../vendor/k8s.io/code-generator/generate-groups.sh \
#   all \
#   $PROJECT_ROOT/pkg/client/testmachinery \
#   $PROJECT_ROOT/pkg/apis \
#   testmachinery:v1beta1 \
#   -h $(dirname $0)/boilerplate.go.txt