#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# this file parses the testmachinery helm chart and adjusts the corresponding version

import sys
import pathlib
import yaml


version=sys.argv[1]

source_path=pathlib.Path(__file__).parent.absolute()
tm_helm_chart_path=pathlib.Path(source_path, "../charts/testmachinery")

with open(pathlib.Path(tm_helm_chart_path, "Chart.yaml")) as file:
    chart = yaml.safe_load(file)
    chart['version'] = version
    print(yaml.dump(chart, default_flow_style=False, sort_keys=False))

with open(pathlib.Path(tm_helm_chart_path, "values.yaml")) as file:
    values = yaml.safe_load(file)
    values['controller']['tag'] = version
    print(yaml.dump(values, default_flow_style=False, sort_keys=False))




