#!/usr/bin/env python3
#
# Copyright 2019 Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# this file parses the testmachinery helm chart and adjusts the corresponding version

import sys
import pathlib
import yaml


version=sys.argv[1]

source_path=pathlib.Path(__file__).parent.absolute()
tm_helm_chart_path=pathlib.Path(source_path, "../charts/testmachinery")

with open(pathlib.Path(tm_helm_chart_path, "Chart.yaml")) as file:
    chart = yaml.safe_load(file)
    chart['version'] = version
    print(yaml.dump(chart, default_flow_style=False, sort_keys=False))

with open(pathlib.Path(tm_helm_chart_path, "values.yaml")) as file:
    values = yaml.safe_load(file)
    values['controller']['tag'] = version
    print(yaml.dump(values, default_flow_style=False, sort_keys=False))




