//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	types "k8s.io/apimachinery/pkg/types"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DowntimePeriods) DeepCopyInto(out *DowntimePeriods) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DowntimePeriods.
func (in *DowntimePeriods) DeepCopy() *DowntimePeriods {
	if in == nil {
		return nil
	}
	out := new(DowntimePeriods)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponseTimeDuration) DeepCopyInto(out *ResponseTimeDuration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResponseTimeDuration.
func (in *ResponseTimeDuration) DeepCopy() *ResponseTimeDuration {
	if in == nil {
		return nil
	}
	out := new(ResponseTimeDuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShootMeasurementData) DeepCopyInto(out *ShootMeasurementData) {
	*out = *in
	out.Shoot = in.Shoot
	if in.DownPeriods != nil {
		in, out := &in.DownPeriods, &out.DownPeriods
		*out = new(DowntimePeriods)
		**out = **in
	}
	if in.ResponseTimeDuration != nil {
		in, out := &in.ResponseTimeDuration, &out.ResponseTimeDuration
		*out = new(ResponseTimeDuration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShootMeasurementData.
func (in *ShootMeasurementData) DeepCopy() *ShootMeasurementData {
	if in == nil {
		return nil
	}
	out := new(ShootMeasurementData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShootsMeasurement) DeepCopyInto(out *ShootsMeasurement) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShootsMeasurement.
func (in *ShootsMeasurement) DeepCopy() *ShootsMeasurement {
	if in == nil {
		return nil
	}
	out := new(ShootsMeasurement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShootsMeasurement) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShootsMeasurementList) DeepCopyInto(out *ShootsMeasurementList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShootsMeasurement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShootsMeasurementList.
func (in *ShootsMeasurementList) DeepCopy() *ShootsMeasurementList {
	if in == nil {
		return nil
	}
	out := new(ShootsMeasurementList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShootsMeasurementList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShootsMeasurementSpec) DeepCopyInto(out *ShootsMeasurementSpec) {
	*out = *in
	if in.Shoots != nil {
		in, out := &in.Shoots, &out.Shoots
		*out = make([]types.NamespacedName, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShootsMeasurementSpec.
func (in *ShootsMeasurementSpec) DeepCopy() *ShootsMeasurementSpec {
	if in == nil {
		return nil
	}
	out := new(ShootsMeasurementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShootsMeasurementStatus) DeepCopyInto(out *ShootsMeasurementStatus) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make([]ShootMeasurementData, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShootsMeasurementStatus.
func (in *ShootsMeasurementStatus) DeepCopy() *ShootsMeasurementStatus {
	if in == nil {
		return nil
	}
	out := new(ShootsMeasurementStatus)
	in.DeepCopyInto(out)
	return out
}
