# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
name: logging
version: 0.1.0
appVersion: "1.0"
description: "Logging for TestMachinery based on loki and promtail"
