# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.imageVectorOverwrite }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testmachinery-controller-imagevector-overwrite
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "defaultLabels" . | nindent 4 }}
data:
  images_overwrite.yaml: |
{{ .Values.imageVectorOverwrite | indent 4 }}
{{- end }}