# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

{{- $relnamespace := .Release.Namespace -}}
{{- range .Values.testmachinery.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.name}}
  namespace: {{$relnamespace}}
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: {{.dockerconfigjson}}
---
{{- end }}