# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.testmachinery.github.credentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tm-github
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "defaultLabels" . | nindent 4 }}
type: Opaque
data:
  github-secrets.yaml: {{ .Values.testmachinery.github.credentials }}
{{ end }}