# SPDX-FileCopyrightText: Copyright Contributors to the Gardener project
#
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.testmachinery.landscapeMappings }}
{{- range .Values.testmachinery.landscapeMappings }}
{{- if ne .namespace $.Release.Namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
  labels:
    type: argo-wf-managed-namespace
    {{- include "defaultLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}