{{/*
  contains adiitional rbac roles for the gardener resource manager that deploys needed additional software components.
*/}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tm-grm
  labels:
    {{- include "defaultLabels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - rbac.authorization.k8s.io
  - policy
  - apps
  - apiextensions.k8s.io
  - networking.k8s.io
  - extensions
  - autoscaling
  - scheduling.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tm-grm
  labels:
    {{- include "defaultLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tm-grm
subjects:
- kind: ServiceAccount
  name: gardener-resource-manager
  namespace: {{ .Release.Namespace }}
