# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0
{{ if .Values.testmachinery.landscapeMappings }}
{{ range .Values.testmachinery.landscapeMappings }}
{{- if ne .namespace $.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-wf-binding
  namespace: {{ .namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflow-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .namespace }}
{{ end }}
{{ end }}
{{ end }}