# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Secret
metadata:
  name: testmachinery-controller-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "defaultLabels" . | nindent 4 }}
type: Opaque
data:
  tls.crt: {{ required ".Values.controller.tls.crt is required" (b64enc .Values.controller.tls.crt) }}
  tls.key: {{ required ".Values.controller.tls.key is required" (b64enc .Values.controller.tls.key) }}
