# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Secret
metadata:
  name: tm-configuration
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "defaultLabels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ include "config" . | b64enc | trim }}