# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0
{{ if .Values.testmachinery.landscapeMappings }}
{{ range .Values.testmachinery.landscapeMappings }}
{{- if ne .namespace $.Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.argo.objectStorage.secret.name }}
  namespace: {{ .namespace }}
  labels:
    type: argo-wf-managed-namespace
  {{- include "defaultLabels" $ | nindent 4 }}
type: Opaque
stringData:
  accessKey: {{ required "Missing an entry for .Values.global.s3Configuration.accessKey!" $.Values.global.s3Configuration.accessKey }}
  secretKey: {{ required "Missing an entry for .Values.global.s3Configuration.accessKey!" $.Values.global.s3Configuration.secretKey }}
{{ end }}
{{ end }}
{{ end }}