# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Service
metadata:
  name: testmachinery-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "defaultLabels" . | nindent 4 }}
spec:
  selector:
    app: tm-controller
  ports:
  - name: metrics
    protocol: TCP
    port: {{.Values.controller.metricsEndpointPort}}
    targetPort: {{.Values.controller.metricsEndpointPort}}
  - name: webhook
    protocol: TCP
    port: 443
    targetPort: {{.Values.controller.webhook.port}}
