// +build !ignore_autogenerated

/*
Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	json "encoding/json"
	unsafe "unsafe"

	config "github.com/gardener/test-infra/pkg/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ArgoConfiguration)(nil), (*config.ArgoConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ArgoConfiguration_To_config_ArgoConfiguration(a.(*ArgoConfiguration), b.(*config.ArgoConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ArgoConfiguration)(nil), (*ArgoConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ArgoConfiguration_To_v1beta1_ArgoConfiguration(a.(*config.ArgoConfiguration), b.(*ArgoConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ArgoUIConfiguration)(nil), (*config.ArgoUIConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ArgoUIConfiguration_To_config_ArgoUIConfiguration(a.(*ArgoUIConfiguration), b.(*config.ArgoUIConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ArgoUIConfiguration)(nil), (*ArgoUIConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ArgoUIConfiguration_To_v1beta1_ArgoUIConfiguration(a.(*config.ArgoUIConfiguration), b.(*ArgoUIConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Configuration)(nil), (*config.Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Configuration_To_config_Configuration(a.(*Configuration), b.(*config.Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Configuration)(nil), (*Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Configuration_To_v1beta1_Configuration(a.(*config.Configuration), b.(*Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControllerConfig)(nil), (*config.ControllerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ControllerConfig_To_config_ControllerConfig(a.(*ControllerConfig), b.(*config.ControllerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ControllerConfig)(nil), (*ControllerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ControllerConfig_To_v1beta1_ControllerConfig(a.(*config.ControllerConfig), b.(*ControllerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ElasticSearchConfiguration)(nil), (*config.ElasticSearchConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ElasticSearchConfiguration_To_config_ElasticSearchConfiguration(a.(*ElasticSearchConfiguration), b.(*config.ElasticSearchConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ElasticSearchConfiguration)(nil), (*ElasticSearchConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ElasticSearchConfiguration_To_v1beta1_ElasticSearchConfiguration(a.(*config.ElasticSearchConfiguration), b.(*ElasticSearchConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GitHubCacheConfig)(nil), (*config.GitHubCacheConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_GitHubCacheConfig_To_config_GitHubCacheConfig(a.(*GitHubCacheConfig), b.(*config.GitHubCacheConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.GitHubCacheConfig)(nil), (*GitHubCacheConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_GitHubCacheConfig_To_v1beta1_GitHubCacheConfig(a.(*config.GitHubCacheConfig), b.(*GitHubCacheConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GitHubConfig)(nil), (*config.GitHubConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_GitHubConfig_To_config_GitHubConfig(a.(*GitHubConfig), b.(*config.GitHubConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.GitHubConfig)(nil), (*GitHubConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_GitHubConfig_To_v1beta1_GitHubConfig(a.(*config.GitHubConfig), b.(*GitHubConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IngressConfiguration)(nil), (*config.IngressConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_IngressConfiguration_To_config_IngressConfiguration(a.(*IngressConfiguration), b.(*config.IngressConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.IngressConfiguration)(nil), (*IngressConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_IngressConfiguration_To_v1beta1_IngressConfiguration(a.(*config.IngressConfiguration), b.(*IngressConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MinioConfiguration)(nil), (*config.MinioConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MinioConfiguration_To_config_MinioConfiguration(a.(*MinioConfiguration), b.(*config.MinioConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.MinioConfiguration)(nil), (*MinioConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_MinioConfiguration_To_v1beta1_MinioConfiguration(a.(*config.MinioConfiguration), b.(*MinioConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S3Configuration)(nil), (*config.S3Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_S3Configuration_To_config_S3Configuration(a.(*S3Configuration), b.(*config.S3Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.S3Configuration)(nil), (*S3Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_S3Configuration_To_v1beta1_S3Configuration(a.(*config.S3Configuration), b.(*S3Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S3ServerConfiguration)(nil), (*config.S3ServerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_S3ServerConfiguration_To_config_S3ServerConfiguration(a.(*S3ServerConfiguration), b.(*config.S3ServerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.S3ServerConfiguration)(nil), (*S3ServerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_S3ServerConfiguration_To_v1beta1_S3ServerConfiguration(a.(*config.S3ServerConfiguration), b.(*S3ServerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TestMachineryConfiguration)(nil), (*config.TestMachineryConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TestMachineryConfiguration_To_config_TestMachineryConfiguration(a.(*TestMachineryConfiguration), b.(*config.TestMachineryConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.TestMachineryConfiguration)(nil), (*TestMachineryConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_TestMachineryConfiguration_To_v1beta1_TestMachineryConfiguration(a.(*config.TestMachineryConfiguration), b.(*TestMachineryConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WebhookConfig)(nil), (*config.WebhookConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_WebhookConfig_To_config_WebhookConfig(a.(*WebhookConfig), b.(*config.WebhookConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.WebhookConfig)(nil), (*WebhookConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_WebhookConfig_To_v1beta1_WebhookConfig(a.(*config.WebhookConfig), b.(*WebhookConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_ArgoConfiguration_To_config_ArgoConfiguration(in *ArgoConfiguration, out *config.ArgoConfiguration, s conversion.Scope) error {
	if err := Convert_v1beta1_ArgoUIConfiguration_To_config_ArgoUIConfiguration(&in.ArgoUI, &out.ArgoUI, s); err != nil {
		return err
	}
	out.ChartValues = *(*json.RawMessage)(unsafe.Pointer(&in.ChartValues))
	return nil
}

// Convert_v1beta1_ArgoConfiguration_To_config_ArgoConfiguration is an autogenerated conversion function.
func Convert_v1beta1_ArgoConfiguration_To_config_ArgoConfiguration(in *ArgoConfiguration, out *config.ArgoConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta1_ArgoConfiguration_To_config_ArgoConfiguration(in, out, s)
}

func autoConvert_config_ArgoConfiguration_To_v1beta1_ArgoConfiguration(in *config.ArgoConfiguration, out *ArgoConfiguration, s conversion.Scope) error {
	if err := Convert_config_ArgoUIConfiguration_To_v1beta1_ArgoUIConfiguration(&in.ArgoUI, &out.ArgoUI, s); err != nil {
		return err
	}
	out.ChartValues = *(*json.RawMessage)(unsafe.Pointer(&in.ChartValues))
	return nil
}

// Convert_config_ArgoConfiguration_To_v1beta1_ArgoConfiguration is an autogenerated conversion function.
func Convert_config_ArgoConfiguration_To_v1beta1_ArgoConfiguration(in *config.ArgoConfiguration, out *ArgoConfiguration, s conversion.Scope) error {
	return autoConvert_config_ArgoConfiguration_To_v1beta1_ArgoConfiguration(in, out, s)
}

func autoConvert_v1beta1_ArgoUIConfiguration_To_config_ArgoUIConfiguration(in *ArgoUIConfiguration, out *config.ArgoUIConfiguration, s conversion.Scope) error {
	if err := Convert_v1beta1_IngressConfiguration_To_config_IngressConfiguration(&in.Ingress, &out.Ingress, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_ArgoUIConfiguration_To_config_ArgoUIConfiguration is an autogenerated conversion function.
func Convert_v1beta1_ArgoUIConfiguration_To_config_ArgoUIConfiguration(in *ArgoUIConfiguration, out *config.ArgoUIConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta1_ArgoUIConfiguration_To_config_ArgoUIConfiguration(in, out, s)
}

func autoConvert_config_ArgoUIConfiguration_To_v1beta1_ArgoUIConfiguration(in *config.ArgoUIConfiguration, out *ArgoUIConfiguration, s conversion.Scope) error {
	if err := Convert_config_IngressConfiguration_To_v1beta1_IngressConfiguration(&in.Ingress, &out.Ingress, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_ArgoUIConfiguration_To_v1beta1_ArgoUIConfiguration is an autogenerated conversion function.
func Convert_config_ArgoUIConfiguration_To_v1beta1_ArgoUIConfiguration(in *config.ArgoUIConfiguration, out *ArgoUIConfiguration, s conversion.Scope) error {
	return autoConvert_config_ArgoUIConfiguration_To_v1beta1_ArgoUIConfiguration(in, out, s)
}

func autoConvert_v1beta1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	if err := Convert_v1beta1_ControllerConfig_To_config_ControllerConfig(&in.ControllerConfig, &out.ControllerConfig, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_TestMachineryConfiguration_To_config_TestMachineryConfiguration(&in.TestMachineryConfiguration, &out.TestMachineryConfiguration, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_GitHubConfig_To_config_GitHubConfig(&in.GitHub, &out.GitHub, s); err != nil {
		return err
	}
	out.S3Configuration = (*config.S3Configuration)(unsafe.Pointer(in.S3Configuration))
	out.ElasticSearchConfiguration = (*config.ElasticSearchConfiguration)(unsafe.Pointer(in.ElasticSearchConfiguration))
	if err := Convert_v1beta1_ArgoConfiguration_To_config_ArgoConfiguration(&in.Argo, &out.Argo, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Configuration_To_config_Configuration is an autogenerated conversion function.
func Convert_v1beta1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	return autoConvert_v1beta1_Configuration_To_config_Configuration(in, out, s)
}

func autoConvert_config_Configuration_To_v1beta1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	if err := Convert_config_ControllerConfig_To_v1beta1_ControllerConfig(&in.ControllerConfig, &out.ControllerConfig, s); err != nil {
		return err
	}
	if err := Convert_config_TestMachineryConfiguration_To_v1beta1_TestMachineryConfiguration(&in.TestMachineryConfiguration, &out.TestMachineryConfiguration, s); err != nil {
		return err
	}
	if err := Convert_config_GitHubConfig_To_v1beta1_GitHubConfig(&in.GitHub, &out.GitHub, s); err != nil {
		return err
	}
	out.S3Configuration = (*S3Configuration)(unsafe.Pointer(in.S3Configuration))
	out.ElasticSearchConfiguration = (*ElasticSearchConfiguration)(unsafe.Pointer(in.ElasticSearchConfiguration))
	if err := Convert_config_ArgoConfiguration_To_v1beta1_ArgoConfiguration(&in.Argo, &out.Argo, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_Configuration_To_v1beta1_Configuration is an autogenerated conversion function.
func Convert_config_Configuration_To_v1beta1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	return autoConvert_config_Configuration_To_v1beta1_Configuration(in, out, s)
}

func autoConvert_v1beta1_ControllerConfig_To_config_ControllerConfig(in *ControllerConfig, out *config.ControllerConfig, s conversion.Scope) error {
	out.HealthAddr = in.HealthAddr
	out.MetricsAddr = in.MetricsAddr
	out.EnableLeaderElection = in.EnableLeaderElection
	out.MaxConcurrentSyncs = in.MaxConcurrentSyncs
	if err := Convert_v1beta1_WebhookConfig_To_config_WebhookConfig(&in.WebhookConfig, &out.WebhookConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_ControllerConfig_To_config_ControllerConfig is an autogenerated conversion function.
func Convert_v1beta1_ControllerConfig_To_config_ControllerConfig(in *ControllerConfig, out *config.ControllerConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_ControllerConfig_To_config_ControllerConfig(in, out, s)
}

func autoConvert_config_ControllerConfig_To_v1beta1_ControllerConfig(in *config.ControllerConfig, out *ControllerConfig, s conversion.Scope) error {
	out.HealthAddr = in.HealthAddr
	out.MetricsAddr = in.MetricsAddr
	out.EnableLeaderElection = in.EnableLeaderElection
	out.MaxConcurrentSyncs = in.MaxConcurrentSyncs
	if err := Convert_config_WebhookConfig_To_v1beta1_WebhookConfig(&in.WebhookConfig, &out.WebhookConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_ControllerConfig_To_v1beta1_ControllerConfig is an autogenerated conversion function.
func Convert_config_ControllerConfig_To_v1beta1_ControllerConfig(in *config.ControllerConfig, out *ControllerConfig, s conversion.Scope) error {
	return autoConvert_config_ControllerConfig_To_v1beta1_ControllerConfig(in, out, s)
}

func autoConvert_v1beta1_ElasticSearchConfiguration_To_config_ElasticSearchConfiguration(in *ElasticSearchConfiguration, out *config.ElasticSearchConfiguration, s conversion.Scope) error {
	out.Endpoint = in.Endpoint
	out.Username = in.Username
	out.Password = in.Password
	return nil
}

// Convert_v1beta1_ElasticSearchConfiguration_To_config_ElasticSearchConfiguration is an autogenerated conversion function.
func Convert_v1beta1_ElasticSearchConfiguration_To_config_ElasticSearchConfiguration(in *ElasticSearchConfiguration, out *config.ElasticSearchConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta1_ElasticSearchConfiguration_To_config_ElasticSearchConfiguration(in, out, s)
}

func autoConvert_config_ElasticSearchConfiguration_To_v1beta1_ElasticSearchConfiguration(in *config.ElasticSearchConfiguration, out *ElasticSearchConfiguration, s conversion.Scope) error {
	out.Endpoint = in.Endpoint
	out.Username = in.Username
	out.Password = in.Password
	return nil
}

// Convert_config_ElasticSearchConfiguration_To_v1beta1_ElasticSearchConfiguration is an autogenerated conversion function.
func Convert_config_ElasticSearchConfiguration_To_v1beta1_ElasticSearchConfiguration(in *config.ElasticSearchConfiguration, out *ElasticSearchConfiguration, s conversion.Scope) error {
	return autoConvert_config_ElasticSearchConfiguration_To_v1beta1_ElasticSearchConfiguration(in, out, s)
}

func autoConvert_v1beta1_GitHubCacheConfig_To_config_GitHubCacheConfig(in *GitHubCacheConfig, out *config.GitHubCacheConfig, s conversion.Scope) error {
	out.CacheDir = in.CacheDir
	out.CacheDiskSizeGB = in.CacheDiskSizeGB
	out.MaxAgeSeconds = in.MaxAgeSeconds
	return nil
}

// Convert_v1beta1_GitHubCacheConfig_To_config_GitHubCacheConfig is an autogenerated conversion function.
func Convert_v1beta1_GitHubCacheConfig_To_config_GitHubCacheConfig(in *GitHubCacheConfig, out *config.GitHubCacheConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_GitHubCacheConfig_To_config_GitHubCacheConfig(in, out, s)
}

func autoConvert_config_GitHubCacheConfig_To_v1beta1_GitHubCacheConfig(in *config.GitHubCacheConfig, out *GitHubCacheConfig, s conversion.Scope) error {
	out.CacheDir = in.CacheDir
	out.CacheDiskSizeGB = in.CacheDiskSizeGB
	out.MaxAgeSeconds = in.MaxAgeSeconds
	return nil
}

// Convert_config_GitHubCacheConfig_To_v1beta1_GitHubCacheConfig is an autogenerated conversion function.
func Convert_config_GitHubCacheConfig_To_v1beta1_GitHubCacheConfig(in *config.GitHubCacheConfig, out *GitHubCacheConfig, s conversion.Scope) error {
	return autoConvert_config_GitHubCacheConfig_To_v1beta1_GitHubCacheConfig(in, out, s)
}

func autoConvert_v1beta1_GitHubConfig_To_config_GitHubConfig(in *GitHubConfig, out *config.GitHubConfig, s conversion.Scope) error {
	out.Cache = (*config.GitHubCacheConfig)(unsafe.Pointer(in.Cache))
	out.SecretsPath = in.SecretsPath
	return nil
}

// Convert_v1beta1_GitHubConfig_To_config_GitHubConfig is an autogenerated conversion function.
func Convert_v1beta1_GitHubConfig_To_config_GitHubConfig(in *GitHubConfig, out *config.GitHubConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_GitHubConfig_To_config_GitHubConfig(in, out, s)
}

func autoConvert_config_GitHubConfig_To_v1beta1_GitHubConfig(in *config.GitHubConfig, out *GitHubConfig, s conversion.Scope) error {
	out.Cache = (*GitHubCacheConfig)(unsafe.Pointer(in.Cache))
	out.SecretsPath = in.SecretsPath
	return nil
}

// Convert_config_GitHubConfig_To_v1beta1_GitHubConfig is an autogenerated conversion function.
func Convert_config_GitHubConfig_To_v1beta1_GitHubConfig(in *config.GitHubConfig, out *GitHubConfig, s conversion.Scope) error {
	return autoConvert_config_GitHubConfig_To_v1beta1_GitHubConfig(in, out, s)
}

func autoConvert_v1beta1_IngressConfiguration_To_config_IngressConfiguration(in *IngressConfiguration, out *config.IngressConfiguration, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Host = in.Host
	return nil
}

// Convert_v1beta1_IngressConfiguration_To_config_IngressConfiguration is an autogenerated conversion function.
func Convert_v1beta1_IngressConfiguration_To_config_IngressConfiguration(in *IngressConfiguration, out *config.IngressConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta1_IngressConfiguration_To_config_IngressConfiguration(in, out, s)
}

func autoConvert_config_IngressConfiguration_To_v1beta1_IngressConfiguration(in *config.IngressConfiguration, out *IngressConfiguration, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Host = in.Host
	return nil
}

// Convert_config_IngressConfiguration_To_v1beta1_IngressConfiguration is an autogenerated conversion function.
func Convert_config_IngressConfiguration_To_v1beta1_IngressConfiguration(in *config.IngressConfiguration, out *IngressConfiguration, s conversion.Scope) error {
	return autoConvert_config_IngressConfiguration_To_v1beta1_IngressConfiguration(in, out, s)
}

func autoConvert_v1beta1_MinioConfiguration_To_config_MinioConfiguration(in *MinioConfiguration, out *config.MinioConfiguration, s conversion.Scope) error {
	out.Distributed = in.Distributed
	if err := Convert_v1beta1_IngressConfiguration_To_config_IngressConfiguration(&in.Ingress, &out.Ingress, s); err != nil {
		return err
	}
	out.ChartValues = *(*json.RawMessage)(unsafe.Pointer(&in.ChartValues))
	return nil
}

// Convert_v1beta1_MinioConfiguration_To_config_MinioConfiguration is an autogenerated conversion function.
func Convert_v1beta1_MinioConfiguration_To_config_MinioConfiguration(in *MinioConfiguration, out *config.MinioConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta1_MinioConfiguration_To_config_MinioConfiguration(in, out, s)
}

func autoConvert_config_MinioConfiguration_To_v1beta1_MinioConfiguration(in *config.MinioConfiguration, out *MinioConfiguration, s conversion.Scope) error {
	out.Distributed = in.Distributed
	if err := Convert_config_IngressConfiguration_To_v1beta1_IngressConfiguration(&in.Ingress, &out.Ingress, s); err != nil {
		return err
	}
	out.ChartValues = *(*json.RawMessage)(unsafe.Pointer(&in.ChartValues))
	return nil
}

// Convert_config_MinioConfiguration_To_v1beta1_MinioConfiguration is an autogenerated conversion function.
func Convert_config_MinioConfiguration_To_v1beta1_MinioConfiguration(in *config.MinioConfiguration, out *MinioConfiguration, s conversion.Scope) error {
	return autoConvert_config_MinioConfiguration_To_v1beta1_MinioConfiguration(in, out, s)
}

func autoConvert_v1beta1_S3Configuration_To_config_S3Configuration(in *S3Configuration, out *config.S3Configuration, s conversion.Scope) error {
	if err := Convert_v1beta1_S3ServerConfiguration_To_config_S3ServerConfiguration(&in.Server, &out.Server, s); err != nil {
		return err
	}
	out.BucketName = in.BucketName
	out.AccessKey = in.AccessKey
	out.SecretKey = in.SecretKey
	return nil
}

// Convert_v1beta1_S3Configuration_To_config_S3Configuration is an autogenerated conversion function.
func Convert_v1beta1_S3Configuration_To_config_S3Configuration(in *S3Configuration, out *config.S3Configuration, s conversion.Scope) error {
	return autoConvert_v1beta1_S3Configuration_To_config_S3Configuration(in, out, s)
}

func autoConvert_config_S3Configuration_To_v1beta1_S3Configuration(in *config.S3Configuration, out *S3Configuration, s conversion.Scope) error {
	if err := Convert_config_S3ServerConfiguration_To_v1beta1_S3ServerConfiguration(&in.Server, &out.Server, s); err != nil {
		return err
	}
	out.BucketName = in.BucketName
	out.AccessKey = in.AccessKey
	out.SecretKey = in.SecretKey
	return nil
}

// Convert_config_S3Configuration_To_v1beta1_S3Configuration is an autogenerated conversion function.
func Convert_config_S3Configuration_To_v1beta1_S3Configuration(in *config.S3Configuration, out *S3Configuration, s conversion.Scope) error {
	return autoConvert_config_S3Configuration_To_v1beta1_S3Configuration(in, out, s)
}

func autoConvert_v1beta1_S3ServerConfiguration_To_config_S3ServerConfiguration(in *S3ServerConfiguration, out *config.S3ServerConfiguration, s conversion.Scope) error {
	out.Minio = (*config.MinioConfiguration)(unsafe.Pointer(in.Minio))
	out.Endpoint = in.Endpoint
	out.SSL = in.SSL
	return nil
}

// Convert_v1beta1_S3ServerConfiguration_To_config_S3ServerConfiguration is an autogenerated conversion function.
func Convert_v1beta1_S3ServerConfiguration_To_config_S3ServerConfiguration(in *S3ServerConfiguration, out *config.S3ServerConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta1_S3ServerConfiguration_To_config_S3ServerConfiguration(in, out, s)
}

func autoConvert_config_S3ServerConfiguration_To_v1beta1_S3ServerConfiguration(in *config.S3ServerConfiguration, out *S3ServerConfiguration, s conversion.Scope) error {
	out.Minio = (*MinioConfiguration)(unsafe.Pointer(in.Minio))
	out.Endpoint = in.Endpoint
	out.SSL = in.SSL
	return nil
}

// Convert_config_S3ServerConfiguration_To_v1beta1_S3ServerConfiguration is an autogenerated conversion function.
func Convert_config_S3ServerConfiguration_To_v1beta1_S3ServerConfiguration(in *config.S3ServerConfiguration, out *S3ServerConfiguration, s conversion.Scope) error {
	return autoConvert_config_S3ServerConfiguration_To_v1beta1_S3ServerConfiguration(in, out, s)
}

func autoConvert_v1beta1_TestMachineryConfiguration_To_config_TestMachineryConfiguration(in *TestMachineryConfiguration, out *config.TestMachineryConfiguration, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.TestDefPath = in.TestDefPath
	out.PrepareImage = in.PrepareImage
	out.BaseImage = in.BaseImage
	out.Local = in.Local
	out.Insecure = in.Insecure
	out.DisableCollector = in.DisableCollector
	out.CleanWorkflowPods = in.CleanWorkflowPods
	return nil
}

// Convert_v1beta1_TestMachineryConfiguration_To_config_TestMachineryConfiguration is an autogenerated conversion function.
func Convert_v1beta1_TestMachineryConfiguration_To_config_TestMachineryConfiguration(in *TestMachineryConfiguration, out *config.TestMachineryConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta1_TestMachineryConfiguration_To_config_TestMachineryConfiguration(in, out, s)
}

func autoConvert_config_TestMachineryConfiguration_To_v1beta1_TestMachineryConfiguration(in *config.TestMachineryConfiguration, out *TestMachineryConfiguration, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.TestDefPath = in.TestDefPath
	out.PrepareImage = in.PrepareImage
	out.BaseImage = in.BaseImage
	out.Local = in.Local
	out.Insecure = in.Insecure
	out.DisableCollector = in.DisableCollector
	out.CleanWorkflowPods = in.CleanWorkflowPods
	return nil
}

// Convert_config_TestMachineryConfiguration_To_v1beta1_TestMachineryConfiguration is an autogenerated conversion function.
func Convert_config_TestMachineryConfiguration_To_v1beta1_TestMachineryConfiguration(in *config.TestMachineryConfiguration, out *TestMachineryConfiguration, s conversion.Scope) error {
	return autoConvert_config_TestMachineryConfiguration_To_v1beta1_TestMachineryConfiguration(in, out, s)
}

func autoConvert_v1beta1_WebhookConfig_To_config_WebhookConfig(in *WebhookConfig, out *config.WebhookConfig, s conversion.Scope) error {
	out.Port = in.Port
	out.CertDir = in.CertDir
	return nil
}

// Convert_v1beta1_WebhookConfig_To_config_WebhookConfig is an autogenerated conversion function.
func Convert_v1beta1_WebhookConfig_To_config_WebhookConfig(in *WebhookConfig, out *config.WebhookConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_WebhookConfig_To_config_WebhookConfig(in, out, s)
}

func autoConvert_config_WebhookConfig_To_v1beta1_WebhookConfig(in *config.WebhookConfig, out *WebhookConfig, s conversion.Scope) error {
	out.Port = in.Port
	out.CertDir = in.CertDir
	return nil
}

// Convert_config_WebhookConfig_To_v1beta1_WebhookConfig is an autogenerated conversion function.
func Convert_config_WebhookConfig_To_v1beta1_WebhookConfig(in *config.WebhookConfig, out *WebhookConfig, s conversion.Scope) error {
	return autoConvert_config_WebhookConfig_To_v1beta1_WebhookConfig(in, out, s)
}
