//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"

	config "github.com/gardener/test-infra/pkg/apis/config"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*BotConfiguration)(nil), (*config.BotConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_BotConfiguration_To_config_BotConfiguration(a.(*BotConfiguration), b.(*config.BotConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.BotConfiguration)(nil), (*BotConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_BotConfiguration_To_v1beta1_BotConfiguration(a.(*config.BotConfiguration), b.(*BotConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Certificate)(nil), (*config.Certificate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Certificate_To_config_Certificate(a.(*Certificate), b.(*config.Certificate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Certificate)(nil), (*Certificate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Certificate_To_v1beta1_Certificate(a.(*config.Certificate), b.(*Certificate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Configuration)(nil), (*config.Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Configuration_To_config_Configuration(a.(*Configuration), b.(*config.Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Configuration)(nil), (*Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Configuration_To_v1beta1_Configuration(a.(*config.Configuration), b.(*Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Controller)(nil), (*config.Controller)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Controller_To_config_Controller(a.(*Controller), b.(*config.Controller), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Controller)(nil), (*Controller)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Controller_To_v1beta1_Controller(a.(*config.Controller), b.(*Controller), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Dashboard)(nil), (*config.Dashboard)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Dashboard_To_config_Dashboard(a.(*Dashboard), b.(*config.Dashboard), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Dashboard)(nil), (*Dashboard)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Dashboard_To_v1beta1_Dashboard(a.(*config.Dashboard), b.(*Dashboard), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DashboardAuthentication)(nil), (*config.DashboardAuthentication)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DashboardAuthentication_To_config_DashboardAuthentication(a.(*DashboardAuthentication), b.(*config.DashboardAuthentication), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.DashboardAuthentication)(nil), (*DashboardAuthentication)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_DashboardAuthentication_To_v1beta1_DashboardAuthentication(a.(*config.DashboardAuthentication), b.(*DashboardAuthentication), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ElasticSearch)(nil), (*config.ElasticSearch)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ElasticSearch_To_config_ElasticSearch(a.(*ElasticSearch), b.(*config.ElasticSearch), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ElasticSearch)(nil), (*ElasticSearch)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ElasticSearch_To_v1beta1_ElasticSearch(a.(*config.ElasticSearch), b.(*ElasticSearch), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GitHub)(nil), (*config.GitHub)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_GitHub_To_config_GitHub(a.(*GitHub), b.(*config.GitHub), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.GitHub)(nil), (*GitHub)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_GitHub_To_v1beta1_GitHub(a.(*config.GitHub), b.(*GitHub), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GitHubAuthentication)(nil), (*config.GitHubAuthentication)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_GitHubAuthentication_To_config_GitHubAuthentication(a.(*GitHubAuthentication), b.(*config.GitHubAuthentication), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.GitHubAuthentication)(nil), (*GitHubAuthentication)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_GitHubAuthentication_To_v1beta1_GitHubAuthentication(a.(*config.GitHubAuthentication), b.(*GitHubAuthentication), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GitHubBot)(nil), (*config.GitHubBot)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_GitHubBot_To_config_GitHubBot(a.(*GitHubBot), b.(*config.GitHubBot), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.GitHubBot)(nil), (*GitHubBot)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_GitHubBot_To_v1beta1_GitHubBot(a.(*config.GitHubBot), b.(*GitHubBot), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GitHubCache)(nil), (*config.GitHubCache)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_GitHubCache_To_config_GitHubCache(a.(*GitHubCache), b.(*config.GitHubCache), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.GitHubCache)(nil), (*GitHubCache)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_GitHubCache_To_v1beta1_GitHubCache(a.(*config.GitHubCache), b.(*GitHubCache), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HealthCheckTarget)(nil), (*config.HealthCheckTarget)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HealthCheckTarget_To_config_HealthCheckTarget(a.(*HealthCheckTarget), b.(*config.HealthCheckTarget), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.HealthCheckTarget)(nil), (*HealthCheckTarget)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_HealthCheckTarget_To_v1beta1_HealthCheckTarget(a.(*config.HealthCheckTarget), b.(*HealthCheckTarget), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LandscapeMapping)(nil), (*config.LandscapeMapping)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LandscapeMapping_To_config_LandscapeMapping(a.(*LandscapeMapping), b.(*config.LandscapeMapping), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.LandscapeMapping)(nil), (*LandscapeMapping)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_LandscapeMapping_To_v1beta1_LandscapeMapping(a.(*config.LandscapeMapping), b.(*LandscapeMapping), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Locations)(nil), (*config.Locations)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Locations_To_config_Locations(a.(*Locations), b.(*config.Locations), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Locations)(nil), (*Locations)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Locations_To_v1beta1_Locations(a.(*config.Locations), b.(*Locations), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OAuth)(nil), (*config.OAuth)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OAuth_To_config_OAuth(a.(*OAuth), b.(*config.OAuth), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.OAuth)(nil), (*OAuth)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_OAuth_To_v1beta1_OAuth(a.(*config.OAuth), b.(*OAuth), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S3)(nil), (*config.S3)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_S3_To_config_S3(a.(*S3), b.(*config.S3), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.S3)(nil), (*S3)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_S3_To_v1beta1_S3(a.(*config.S3), b.(*S3), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S3Server)(nil), (*config.S3Server)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_S3Server_To_config_S3Server(a.(*S3Server), b.(*config.S3Server), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.S3Server)(nil), (*S3Server)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_S3Server_To_v1beta1_S3Server(a.(*config.S3Server), b.(*S3Server), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TTLController)(nil), (*config.TTLController)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TTLController_To_config_TTLController(a.(*TTLController), b.(*config.TTLController), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.TTLController)(nil), (*TTLController)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_TTLController_To_v1beta1_TTLController(a.(*config.TTLController), b.(*TTLController), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TestMachinery)(nil), (*config.TestMachinery)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TestMachinery_To_config_TestMachinery(a.(*TestMachinery), b.(*config.TestMachinery), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.TestMachinery)(nil), (*TestMachinery)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_TestMachinery_To_v1beta1_TestMachinery(a.(*config.TestMachinery), b.(*TestMachinery), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WebhookConfig)(nil), (*config.WebhookConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_WebhookConfig_To_config_WebhookConfig(a.(*WebhookConfig), b.(*config.WebhookConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.WebhookConfig)(nil), (*WebhookConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_WebhookConfig_To_v1beta1_WebhookConfig(a.(*config.WebhookConfig), b.(*WebhookConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Webserver)(nil), (*config.Webserver)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Webserver_To_config_Webserver(a.(*Webserver), b.(*config.Webserver), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Webserver)(nil), (*Webserver)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Webserver_To_v1beta1_Webserver(a.(*config.Webserver), b.(*Webserver), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_BotConfiguration_To_config_BotConfiguration(in *BotConfiguration, out *config.BotConfiguration, s conversion.Scope) error {
	if err := Convert_v1beta1_Webserver_To_config_Webserver(&in.Webserver, &out.Webserver, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_Dashboard_To_config_Dashboard(&in.Dashboard, &out.Dashboard, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_GitHubBot_To_config_GitHubBot(&in.GitHubBot, &out.GitHubBot, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_BotConfiguration_To_config_BotConfiguration is an autogenerated conversion function.
func Convert_v1beta1_BotConfiguration_To_config_BotConfiguration(in *BotConfiguration, out *config.BotConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta1_BotConfiguration_To_config_BotConfiguration(in, out, s)
}

func autoConvert_config_BotConfiguration_To_v1beta1_BotConfiguration(in *config.BotConfiguration, out *BotConfiguration, s conversion.Scope) error {
	if err := Convert_config_Webserver_To_v1beta1_Webserver(&in.Webserver, &out.Webserver, s); err != nil {
		return err
	}
	if err := Convert_config_Dashboard_To_v1beta1_Dashboard(&in.Dashboard, &out.Dashboard, s); err != nil {
		return err
	}
	if err := Convert_config_GitHubBot_To_v1beta1_GitHubBot(&in.GitHubBot, &out.GitHubBot, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_BotConfiguration_To_v1beta1_BotConfiguration is an autogenerated conversion function.
func Convert_config_BotConfiguration_To_v1beta1_BotConfiguration(in *config.BotConfiguration, out *BotConfiguration, s conversion.Scope) error {
	return autoConvert_config_BotConfiguration_To_v1beta1_BotConfiguration(in, out, s)
}

func autoConvert_v1beta1_Certificate_To_config_Certificate(in *Certificate, out *config.Certificate, s conversion.Scope) error {
	out.Cert = in.Cert
	out.PrivateKey = in.PrivateKey
	return nil
}

// Convert_v1beta1_Certificate_To_config_Certificate is an autogenerated conversion function.
func Convert_v1beta1_Certificate_To_config_Certificate(in *Certificate, out *config.Certificate, s conversion.Scope) error {
	return autoConvert_v1beta1_Certificate_To_config_Certificate(in, out, s)
}

func autoConvert_config_Certificate_To_v1beta1_Certificate(in *config.Certificate, out *Certificate, s conversion.Scope) error {
	out.Cert = in.Cert
	out.PrivateKey = in.PrivateKey
	return nil
}

// Convert_config_Certificate_To_v1beta1_Certificate is an autogenerated conversion function.
func Convert_config_Certificate_To_v1beta1_Certificate(in *config.Certificate, out *Certificate, s conversion.Scope) error {
	return autoConvert_config_Certificate_To_v1beta1_Certificate(in, out, s)
}

func autoConvert_v1beta1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	if err := Convert_v1beta1_Controller_To_config_Controller(&in.Controller, &out.Controller, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_TestMachinery_To_config_TestMachinery(&in.TestMachinery, &out.TestMachinery, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_GitHub_To_config_GitHub(&in.GitHub, &out.GitHub, s); err != nil {
		return err
	}
	out.S3 = (*config.S3)(unsafe.Pointer(in.S3))
	out.ElasticSearch = (*config.ElasticSearch)(unsafe.Pointer(in.ElasticSearch))
	out.ImagePullSecretNames = *(*[]string)(unsafe.Pointer(&in.ImagePullSecretNames))
	return nil
}

// Convert_v1beta1_Configuration_To_config_Configuration is an autogenerated conversion function.
func Convert_v1beta1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	return autoConvert_v1beta1_Configuration_To_config_Configuration(in, out, s)
}

func autoConvert_config_Configuration_To_v1beta1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	if err := Convert_config_Controller_To_v1beta1_Controller(&in.Controller, &out.Controller, s); err != nil {
		return err
	}
	if err := Convert_config_TestMachinery_To_v1beta1_TestMachinery(&in.TestMachinery, &out.TestMachinery, s); err != nil {
		return err
	}
	if err := Convert_config_GitHub_To_v1beta1_GitHub(&in.GitHub, &out.GitHub, s); err != nil {
		return err
	}
	out.S3 = (*S3)(unsafe.Pointer(in.S3))
	out.ElasticSearch = (*ElasticSearch)(unsafe.Pointer(in.ElasticSearch))
	out.ImagePullSecretNames = *(*[]string)(unsafe.Pointer(&in.ImagePullSecretNames))
	return nil
}

// Convert_config_Configuration_To_v1beta1_Configuration is an autogenerated conversion function.
func Convert_config_Configuration_To_v1beta1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	return autoConvert_config_Configuration_To_v1beta1_Configuration(in, out, s)
}

func autoConvert_v1beta1_Controller_To_config_Controller(in *Controller, out *config.Controller, s conversion.Scope) error {
	out.HealthAddr = in.HealthAddr
	out.MetricsAddr = in.MetricsAddr
	out.EnableLeaderElection = in.EnableLeaderElection
	out.MaxConcurrentSyncs = in.MaxConcurrentSyncs
	if err := Convert_v1beta1_TTLController_To_config_TTLController(&in.TTLController, &out.TTLController, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_WebhookConfig_To_config_WebhookConfig(&in.WebhookConfig, &out.WebhookConfig, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_HealthCheckTarget_To_config_HealthCheckTarget(&in.DependencyHealthCheck, &out.DependencyHealthCheck, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Controller_To_config_Controller is an autogenerated conversion function.
func Convert_v1beta1_Controller_To_config_Controller(in *Controller, out *config.Controller, s conversion.Scope) error {
	return autoConvert_v1beta1_Controller_To_config_Controller(in, out, s)
}

func autoConvert_config_Controller_To_v1beta1_Controller(in *config.Controller, out *Controller, s conversion.Scope) error {
	out.HealthAddr = in.HealthAddr
	out.MetricsAddr = in.MetricsAddr
	out.EnableLeaderElection = in.EnableLeaderElection
	out.MaxConcurrentSyncs = in.MaxConcurrentSyncs
	if err := Convert_config_TTLController_To_v1beta1_TTLController(&in.TTLController, &out.TTLController, s); err != nil {
		return err
	}
	if err := Convert_config_WebhookConfig_To_v1beta1_WebhookConfig(&in.WebhookConfig, &out.WebhookConfig, s); err != nil {
		return err
	}
	if err := Convert_config_HealthCheckTarget_To_v1beta1_HealthCheckTarget(&in.DependencyHealthCheck, &out.DependencyHealthCheck, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_Controller_To_v1beta1_Controller is an autogenerated conversion function.
func Convert_config_Controller_To_v1beta1_Controller(in *config.Controller, out *Controller, s conversion.Scope) error {
	return autoConvert_config_Controller_To_v1beta1_Controller(in, out, s)
}

func autoConvert_v1beta1_Dashboard_To_config_Dashboard(in *Dashboard, out *config.Dashboard, s conversion.Scope) error {
	out.UIBasePath = in.UIBasePath
	if err := Convert_v1beta1_DashboardAuthentication_To_config_DashboardAuthentication(&in.Authentication, &out.Authentication, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Dashboard_To_config_Dashboard is an autogenerated conversion function.
func Convert_v1beta1_Dashboard_To_config_Dashboard(in *Dashboard, out *config.Dashboard, s conversion.Scope) error {
	return autoConvert_v1beta1_Dashboard_To_config_Dashboard(in, out, s)
}

func autoConvert_config_Dashboard_To_v1beta1_Dashboard(in *config.Dashboard, out *Dashboard, s conversion.Scope) error {
	out.UIBasePath = in.UIBasePath
	if err := Convert_config_DashboardAuthentication_To_v1beta1_DashboardAuthentication(&in.Authentication, &out.Authentication, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_Dashboard_To_v1beta1_Dashboard is an autogenerated conversion function.
func Convert_config_Dashboard_To_v1beta1_Dashboard(in *config.Dashboard, out *Dashboard, s conversion.Scope) error {
	return autoConvert_config_Dashboard_To_v1beta1_Dashboard(in, out, s)
}

func autoConvert_v1beta1_DashboardAuthentication_To_config_DashboardAuthentication(in *DashboardAuthentication, out *config.DashboardAuthentication, s conversion.Scope) error {
	out.Provider = config.DashboardAuthenticationProvider(in.Provider)
	out.CookieSecret = in.CookieSecret
	out.GitHub = (*config.GitHubAuthentication)(unsafe.Pointer(in.GitHub))
	return nil
}

// Convert_v1beta1_DashboardAuthentication_To_config_DashboardAuthentication is an autogenerated conversion function.
func Convert_v1beta1_DashboardAuthentication_To_config_DashboardAuthentication(in *DashboardAuthentication, out *config.DashboardAuthentication, s conversion.Scope) error {
	return autoConvert_v1beta1_DashboardAuthentication_To_config_DashboardAuthentication(in, out, s)
}

func autoConvert_config_DashboardAuthentication_To_v1beta1_DashboardAuthentication(in *config.DashboardAuthentication, out *DashboardAuthentication, s conversion.Scope) error {
	out.Provider = DashboardAuthenticationProvider(in.Provider)
	out.CookieSecret = in.CookieSecret
	out.GitHub = (*GitHubAuthentication)(unsafe.Pointer(in.GitHub))
	return nil
}

// Convert_config_DashboardAuthentication_To_v1beta1_DashboardAuthentication is an autogenerated conversion function.
func Convert_config_DashboardAuthentication_To_v1beta1_DashboardAuthentication(in *config.DashboardAuthentication, out *DashboardAuthentication, s conversion.Scope) error {
	return autoConvert_config_DashboardAuthentication_To_v1beta1_DashboardAuthentication(in, out, s)
}

func autoConvert_v1beta1_ElasticSearch_To_config_ElasticSearch(in *ElasticSearch, out *config.ElasticSearch, s conversion.Scope) error {
	out.Endpoint = in.Endpoint
	out.Username = in.Username
	out.Password = in.Password
	return nil
}

// Convert_v1beta1_ElasticSearch_To_config_ElasticSearch is an autogenerated conversion function.
func Convert_v1beta1_ElasticSearch_To_config_ElasticSearch(in *ElasticSearch, out *config.ElasticSearch, s conversion.Scope) error {
	return autoConvert_v1beta1_ElasticSearch_To_config_ElasticSearch(in, out, s)
}

func autoConvert_config_ElasticSearch_To_v1beta1_ElasticSearch(in *config.ElasticSearch, out *ElasticSearch, s conversion.Scope) error {
	out.Endpoint = in.Endpoint
	out.Username = in.Username
	out.Password = in.Password
	return nil
}

// Convert_config_ElasticSearch_To_v1beta1_ElasticSearch is an autogenerated conversion function.
func Convert_config_ElasticSearch_To_v1beta1_ElasticSearch(in *config.ElasticSearch, out *ElasticSearch, s conversion.Scope) error {
	return autoConvert_config_ElasticSearch_To_v1beta1_ElasticSearch(in, out, s)
}

func autoConvert_v1beta1_GitHub_To_config_GitHub(in *GitHub, out *config.GitHub, s conversion.Scope) error {
	out.Cache = (*config.GitHubCache)(unsafe.Pointer(in.Cache))
	out.SecretsPath = in.SecretsPath
	return nil
}

// Convert_v1beta1_GitHub_To_config_GitHub is an autogenerated conversion function.
func Convert_v1beta1_GitHub_To_config_GitHub(in *GitHub, out *config.GitHub, s conversion.Scope) error {
	return autoConvert_v1beta1_GitHub_To_config_GitHub(in, out, s)
}

func autoConvert_config_GitHub_To_v1beta1_GitHub(in *config.GitHub, out *GitHub, s conversion.Scope) error {
	out.Cache = (*GitHubCache)(unsafe.Pointer(in.Cache))
	out.SecretsPath = in.SecretsPath
	return nil
}

// Convert_config_GitHub_To_v1beta1_GitHub is an autogenerated conversion function.
func Convert_config_GitHub_To_v1beta1_GitHub(in *config.GitHub, out *GitHub, s conversion.Scope) error {
	return autoConvert_config_GitHub_To_v1beta1_GitHub(in, out, s)
}

func autoConvert_v1beta1_GitHubAuthentication_To_config_GitHubAuthentication(in *GitHubAuthentication, out *config.GitHubAuthentication, s conversion.Scope) error {
	out.OAuth = (*config.OAuth)(unsafe.Pointer(in.OAuth))
	out.Organization = in.Organization
	return nil
}

// Convert_v1beta1_GitHubAuthentication_To_config_GitHubAuthentication is an autogenerated conversion function.
func Convert_v1beta1_GitHubAuthentication_To_config_GitHubAuthentication(in *GitHubAuthentication, out *config.GitHubAuthentication, s conversion.Scope) error {
	return autoConvert_v1beta1_GitHubAuthentication_To_config_GitHubAuthentication(in, out, s)
}

func autoConvert_config_GitHubAuthentication_To_v1beta1_GitHubAuthentication(in *config.GitHubAuthentication, out *GitHubAuthentication, s conversion.Scope) error {
	out.OAuth = (*OAuth)(unsafe.Pointer(in.OAuth))
	out.Organization = in.Organization
	return nil
}

// Convert_config_GitHubAuthentication_To_v1beta1_GitHubAuthentication is an autogenerated conversion function.
func Convert_config_GitHubAuthentication_To_v1beta1_GitHubAuthentication(in *config.GitHubAuthentication, out *GitHubAuthentication, s conversion.Scope) error {
	return autoConvert_config_GitHubAuthentication_To_v1beta1_GitHubAuthentication(in, out, s)
}

func autoConvert_v1beta1_GitHubBot_To_config_GitHubBot(in *GitHubBot, out *config.GitHubBot, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.ConfigurationFilePath = in.ConfigurationFilePath
	out.DefaultTeam = in.DefaultTeam
	out.ApiUrl = in.ApiUrl
	out.AppID = int64(in.AppID)
	out.AppPrivateKeyPath = in.AppPrivateKeyPath
	out.WebhookSecret = in.WebhookSecret
	if err := Convert_v1beta1_GitHubCache_To_config_GitHubCache(&in.GitHubCache, &out.GitHubCache, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_GitHubBot_To_config_GitHubBot is an autogenerated conversion function.
func Convert_v1beta1_GitHubBot_To_config_GitHubBot(in *GitHubBot, out *config.GitHubBot, s conversion.Scope) error {
	return autoConvert_v1beta1_GitHubBot_To_config_GitHubBot(in, out, s)
}

func autoConvert_config_GitHubBot_To_v1beta1_GitHubBot(in *config.GitHubBot, out *GitHubBot, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.ConfigurationFilePath = in.ConfigurationFilePath
	out.DefaultTeam = in.DefaultTeam
	out.ApiUrl = in.ApiUrl
	out.AppID = int(in.AppID)
	out.AppPrivateKeyPath = in.AppPrivateKeyPath
	out.WebhookSecret = in.WebhookSecret
	if err := Convert_config_GitHubCache_To_v1beta1_GitHubCache(&in.GitHubCache, &out.GitHubCache, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_GitHubBot_To_v1beta1_GitHubBot is an autogenerated conversion function.
func Convert_config_GitHubBot_To_v1beta1_GitHubBot(in *config.GitHubBot, out *GitHubBot, s conversion.Scope) error {
	return autoConvert_config_GitHubBot_To_v1beta1_GitHubBot(in, out, s)
}

func autoConvert_v1beta1_GitHubCache_To_config_GitHubCache(in *GitHubCache, out *config.GitHubCache, s conversion.Scope) error {
	out.CacheDir = in.CacheDir
	out.CacheDiskSizeGB = in.CacheDiskSizeGB
	out.MaxAgeSeconds = in.MaxAgeSeconds
	return nil
}

// Convert_v1beta1_GitHubCache_To_config_GitHubCache is an autogenerated conversion function.
func Convert_v1beta1_GitHubCache_To_config_GitHubCache(in *GitHubCache, out *config.GitHubCache, s conversion.Scope) error {
	return autoConvert_v1beta1_GitHubCache_To_config_GitHubCache(in, out, s)
}

func autoConvert_config_GitHubCache_To_v1beta1_GitHubCache(in *config.GitHubCache, out *GitHubCache, s conversion.Scope) error {
	out.CacheDir = in.CacheDir
	out.CacheDiskSizeGB = in.CacheDiskSizeGB
	out.MaxAgeSeconds = in.MaxAgeSeconds
	return nil
}

// Convert_config_GitHubCache_To_v1beta1_GitHubCache is an autogenerated conversion function.
func Convert_config_GitHubCache_To_v1beta1_GitHubCache(in *config.GitHubCache, out *GitHubCache, s conversion.Scope) error {
	return autoConvert_config_GitHubCache_To_v1beta1_GitHubCache(in, out, s)
}

func autoConvert_v1beta1_HealthCheckTarget_To_config_HealthCheckTarget(in *HealthCheckTarget, out *config.HealthCheckTarget, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.DeploymentName = in.DeploymentName
	out.Interval = in.Interval
	return nil
}

// Convert_v1beta1_HealthCheckTarget_To_config_HealthCheckTarget is an autogenerated conversion function.
func Convert_v1beta1_HealthCheckTarget_To_config_HealthCheckTarget(in *HealthCheckTarget, out *config.HealthCheckTarget, s conversion.Scope) error {
	return autoConvert_v1beta1_HealthCheckTarget_To_config_HealthCheckTarget(in, out, s)
}

func autoConvert_config_HealthCheckTarget_To_v1beta1_HealthCheckTarget(in *config.HealthCheckTarget, out *HealthCheckTarget, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.DeploymentName = in.DeploymentName
	out.Interval = in.Interval
	return nil
}

// Convert_config_HealthCheckTarget_To_v1beta1_HealthCheckTarget is an autogenerated conversion function.
func Convert_config_HealthCheckTarget_To_v1beta1_HealthCheckTarget(in *config.HealthCheckTarget, out *HealthCheckTarget, s conversion.Scope) error {
	return autoConvert_config_HealthCheckTarget_To_v1beta1_HealthCheckTarget(in, out, s)
}

func autoConvert_v1beta1_LandscapeMapping_To_config_LandscapeMapping(in *LandscapeMapping, out *config.LandscapeMapping, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.ApiServerUrl = in.ApiServerUrl
	out.Audience = in.Audience
	out.ExpirationSeconds = in.ExpirationSeconds
	out.AllowUntrustedUsage = in.AllowUntrustedUsage
	return nil
}

// Convert_v1beta1_LandscapeMapping_To_config_LandscapeMapping is an autogenerated conversion function.
func Convert_v1beta1_LandscapeMapping_To_config_LandscapeMapping(in *LandscapeMapping, out *config.LandscapeMapping, s conversion.Scope) error {
	return autoConvert_v1beta1_LandscapeMapping_To_config_LandscapeMapping(in, out, s)
}

func autoConvert_config_LandscapeMapping_To_v1beta1_LandscapeMapping(in *config.LandscapeMapping, out *LandscapeMapping, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.ApiServerUrl = in.ApiServerUrl
	out.Audience = in.Audience
	out.ExpirationSeconds = in.ExpirationSeconds
	out.AllowUntrustedUsage = in.AllowUntrustedUsage
	return nil
}

// Convert_config_LandscapeMapping_To_v1beta1_LandscapeMapping is an autogenerated conversion function.
func Convert_config_LandscapeMapping_To_v1beta1_LandscapeMapping(in *config.LandscapeMapping, out *LandscapeMapping, s conversion.Scope) error {
	return autoConvert_config_LandscapeMapping_To_v1beta1_LandscapeMapping(in, out, s)
}

func autoConvert_v1beta1_Locations_To_config_Locations(in *Locations, out *config.Locations, s conversion.Scope) error {
	out.ExcludeDomains = *(*[]string)(unsafe.Pointer(&in.ExcludeDomains))
	return nil
}

// Convert_v1beta1_Locations_To_config_Locations is an autogenerated conversion function.
func Convert_v1beta1_Locations_To_config_Locations(in *Locations, out *config.Locations, s conversion.Scope) error {
	return autoConvert_v1beta1_Locations_To_config_Locations(in, out, s)
}

func autoConvert_config_Locations_To_v1beta1_Locations(in *config.Locations, out *Locations, s conversion.Scope) error {
	out.ExcludeDomains = *(*[]string)(unsafe.Pointer(&in.ExcludeDomains))
	return nil
}

// Convert_config_Locations_To_v1beta1_Locations is an autogenerated conversion function.
func Convert_config_Locations_To_v1beta1_Locations(in *config.Locations, out *Locations, s conversion.Scope) error {
	return autoConvert_config_Locations_To_v1beta1_Locations(in, out, s)
}

func autoConvert_v1beta1_OAuth_To_config_OAuth(in *OAuth, out *config.OAuth, s conversion.Scope) error {
	out.ClientID = in.ClientID
	out.ClientSecret = in.ClientSecret
	out.RedirectURL = in.RedirectURL
	return nil
}

// Convert_v1beta1_OAuth_To_config_OAuth is an autogenerated conversion function.
func Convert_v1beta1_OAuth_To_config_OAuth(in *OAuth, out *config.OAuth, s conversion.Scope) error {
	return autoConvert_v1beta1_OAuth_To_config_OAuth(in, out, s)
}

func autoConvert_config_OAuth_To_v1beta1_OAuth(in *config.OAuth, out *OAuth, s conversion.Scope) error {
	out.ClientID = in.ClientID
	out.ClientSecret = in.ClientSecret
	out.RedirectURL = in.RedirectURL
	return nil
}

// Convert_config_OAuth_To_v1beta1_OAuth is an autogenerated conversion function.
func Convert_config_OAuth_To_v1beta1_OAuth(in *config.OAuth, out *OAuth, s conversion.Scope) error {
	return autoConvert_config_OAuth_To_v1beta1_OAuth(in, out, s)
}

func autoConvert_v1beta1_S3_To_config_S3(in *S3, out *config.S3, s conversion.Scope) error {
	if err := Convert_v1beta1_S3Server_To_config_S3Server(&in.Server, &out.Server, s); err != nil {
		return err
	}
	out.BucketName = in.BucketName
	out.AccessKey = in.AccessKey
	out.SecretKey = in.SecretKey
	return nil
}

// Convert_v1beta1_S3_To_config_S3 is an autogenerated conversion function.
func Convert_v1beta1_S3_To_config_S3(in *S3, out *config.S3, s conversion.Scope) error {
	return autoConvert_v1beta1_S3_To_config_S3(in, out, s)
}

func autoConvert_config_S3_To_v1beta1_S3(in *config.S3, out *S3, s conversion.Scope) error {
	if err := Convert_config_S3Server_To_v1beta1_S3Server(&in.Server, &out.Server, s); err != nil {
		return err
	}
	out.BucketName = in.BucketName
	out.AccessKey = in.AccessKey
	out.SecretKey = in.SecretKey
	return nil
}

// Convert_config_S3_To_v1beta1_S3 is an autogenerated conversion function.
func Convert_config_S3_To_v1beta1_S3(in *config.S3, out *S3, s conversion.Scope) error {
	return autoConvert_config_S3_To_v1beta1_S3(in, out, s)
}

func autoConvert_v1beta1_S3Server_To_config_S3Server(in *S3Server, out *config.S3Server, s conversion.Scope) error {
	out.Endpoint = in.Endpoint
	out.SSL = in.SSL
	return nil
}

// Convert_v1beta1_S3Server_To_config_S3Server is an autogenerated conversion function.
func Convert_v1beta1_S3Server_To_config_S3Server(in *S3Server, out *config.S3Server, s conversion.Scope) error {
	return autoConvert_v1beta1_S3Server_To_config_S3Server(in, out, s)
}

func autoConvert_config_S3Server_To_v1beta1_S3Server(in *config.S3Server, out *S3Server, s conversion.Scope) error {
	out.Endpoint = in.Endpoint
	out.SSL = in.SSL
	return nil
}

// Convert_config_S3Server_To_v1beta1_S3Server is an autogenerated conversion function.
func Convert_config_S3Server_To_v1beta1_S3Server(in *config.S3Server, out *S3Server, s conversion.Scope) error {
	return autoConvert_config_S3Server_To_v1beta1_S3Server(in, out, s)
}

func autoConvert_v1beta1_TTLController_To_config_TTLController(in *TTLController, out *config.TTLController, s conversion.Scope) error {
	out.Disable = in.Disable
	out.MaxConcurrentSyncs = in.MaxConcurrentSyncs
	return nil
}

// Convert_v1beta1_TTLController_To_config_TTLController is an autogenerated conversion function.
func Convert_v1beta1_TTLController_To_config_TTLController(in *TTLController, out *config.TTLController, s conversion.Scope) error {
	return autoConvert_v1beta1_TTLController_To_config_TTLController(in, out, s)
}

func autoConvert_config_TTLController_To_v1beta1_TTLController(in *config.TTLController, out *TTLController, s conversion.Scope) error {
	out.Disable = in.Disable
	out.MaxConcurrentSyncs = in.MaxConcurrentSyncs
	return nil
}

// Convert_config_TTLController_To_v1beta1_TTLController is an autogenerated conversion function.
func Convert_config_TTLController_To_v1beta1_TTLController(in *config.TTLController, out *TTLController, s conversion.Scope) error {
	return autoConvert_config_TTLController_To_v1beta1_TTLController(in, out, s)
}

func autoConvert_v1beta1_TestMachinery_To_config_TestMachinery(in *TestMachinery, out *config.TestMachinery, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.TestDefPath = in.TestDefPath
	if err := Convert_v1beta1_Locations_To_config_Locations(&in.Locations, &out.Locations, s); err != nil {
		return err
	}
	out.PrepareImage = in.PrepareImage
	out.BaseImage = in.BaseImage
	out.Local = in.Local
	out.Insecure = in.Insecure
	out.RetryTimeout = in.RetryTimeout
	out.RetryTimeoutDuration = (*time.Duration)(unsafe.Pointer(in.RetryTimeoutDuration))
	out.DisableCollector = in.DisableCollector
	out.CleanWorkflowPods = in.CleanWorkflowPods
	out.LandscapeMappings = *(*[]config.LandscapeMapping)(unsafe.Pointer(&in.LandscapeMappings))
	return nil
}

// Convert_v1beta1_TestMachinery_To_config_TestMachinery is an autogenerated conversion function.
func Convert_v1beta1_TestMachinery_To_config_TestMachinery(in *TestMachinery, out *config.TestMachinery, s conversion.Scope) error {
	return autoConvert_v1beta1_TestMachinery_To_config_TestMachinery(in, out, s)
}

func autoConvert_config_TestMachinery_To_v1beta1_TestMachinery(in *config.TestMachinery, out *TestMachinery, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.TestDefPath = in.TestDefPath
	if err := Convert_config_Locations_To_v1beta1_Locations(&in.Locations, &out.Locations, s); err != nil {
		return err
	}
	out.PrepareImage = in.PrepareImage
	out.BaseImage = in.BaseImage
	out.Local = in.Local
	out.Insecure = in.Insecure
	out.RetryTimeout = in.RetryTimeout
	out.RetryTimeoutDuration = (*time.Duration)(unsafe.Pointer(in.RetryTimeoutDuration))
	out.DisableCollector = in.DisableCollector
	out.CleanWorkflowPods = in.CleanWorkflowPods
	out.LandscapeMappings = *(*[]LandscapeMapping)(unsafe.Pointer(&in.LandscapeMappings))
	return nil
}

// Convert_config_TestMachinery_To_v1beta1_TestMachinery is an autogenerated conversion function.
func Convert_config_TestMachinery_To_v1beta1_TestMachinery(in *config.TestMachinery, out *TestMachinery, s conversion.Scope) error {
	return autoConvert_config_TestMachinery_To_v1beta1_TestMachinery(in, out, s)
}

func autoConvert_v1beta1_WebhookConfig_To_config_WebhookConfig(in *WebhookConfig, out *config.WebhookConfig, s conversion.Scope) error {
	out.Port = in.Port
	out.CertDir = in.CertDir
	return nil
}

// Convert_v1beta1_WebhookConfig_To_config_WebhookConfig is an autogenerated conversion function.
func Convert_v1beta1_WebhookConfig_To_config_WebhookConfig(in *WebhookConfig, out *config.WebhookConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_WebhookConfig_To_config_WebhookConfig(in, out, s)
}

func autoConvert_config_WebhookConfig_To_v1beta1_WebhookConfig(in *config.WebhookConfig, out *WebhookConfig, s conversion.Scope) error {
	out.Port = in.Port
	out.CertDir = in.CertDir
	return nil
}

// Convert_config_WebhookConfig_To_v1beta1_WebhookConfig is an autogenerated conversion function.
func Convert_config_WebhookConfig_To_v1beta1_WebhookConfig(in *config.WebhookConfig, out *WebhookConfig, s conversion.Scope) error {
	return autoConvert_config_WebhookConfig_To_v1beta1_WebhookConfig(in, out, s)
}

func autoConvert_v1beta1_Webserver_To_config_Webserver(in *Webserver, out *config.Webserver, s conversion.Scope) error {
	out.HTTPPort = in.HTTPPort
	out.HTTPSPort = in.HTTPSPort
	if err := Convert_v1beta1_Certificate_To_config_Certificate(&in.Certificate, &out.Certificate, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Webserver_To_config_Webserver is an autogenerated conversion function.
func Convert_v1beta1_Webserver_To_config_Webserver(in *Webserver, out *config.Webserver, s conversion.Scope) error {
	return autoConvert_v1beta1_Webserver_To_config_Webserver(in, out, s)
}

func autoConvert_config_Webserver_To_v1beta1_Webserver(in *config.Webserver, out *Webserver, s conversion.Scope) error {
	out.HTTPPort = in.HTTPPort
	out.HTTPSPort = in.HTTPSPort
	if err := Convert_config_Certificate_To_v1beta1_Certificate(&in.Certificate, &out.Certificate, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_Webserver_To_v1beta1_Webserver is an autogenerated conversion function.
func Convert_config_Webserver_To_v1beta1_Webserver(in *config.Webserver, out *Webserver, s conversion.Scope) error {
	return autoConvert_config_Webserver_To_v1beta1_Webserver(in, out, s)
}
