// +build !ignore_autogenerated

/*
Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	json "encoding/json"
	unsafe "unsafe"

	config "github.com/gardener/test-infra/pkg/apis/config"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Argo)(nil), (*config.Argo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Argo_To_config_Argo(a.(*Argo), b.(*config.Argo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Argo)(nil), (*Argo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Argo_To_v1beta1_Argo(a.(*config.Argo), b.(*Argo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ArgoUI)(nil), (*config.ArgoUI)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ArgoUI_To_config_ArgoUI(a.(*ArgoUI), b.(*config.ArgoUI), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ArgoUI)(nil), (*ArgoUI)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ArgoUI_To_v1beta1_ArgoUI(a.(*config.ArgoUI), b.(*ArgoUI), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Configuration)(nil), (*config.Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Configuration_To_config_Configuration(a.(*Configuration), b.(*config.Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Configuration)(nil), (*Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Configuration_To_v1beta1_Configuration(a.(*config.Configuration), b.(*Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Controller)(nil), (*config.Controller)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Controller_To_config_Controller(a.(*Controller), b.(*config.Controller), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Controller)(nil), (*Controller)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Controller_To_v1beta1_Controller(a.(*config.Controller), b.(*Controller), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ElasticSearch)(nil), (*config.ElasticSearch)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ElasticSearch_To_config_ElasticSearch(a.(*ElasticSearch), b.(*config.ElasticSearch), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ElasticSearch)(nil), (*ElasticSearch)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ElasticSearch_To_v1beta1_ElasticSearch(a.(*config.ElasticSearch), b.(*ElasticSearch), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GitHub)(nil), (*config.GitHub)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_GitHub_To_config_GitHub(a.(*GitHub), b.(*config.GitHub), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.GitHub)(nil), (*GitHub)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_GitHub_To_v1beta1_GitHub(a.(*config.GitHub), b.(*GitHub), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GitHubCache)(nil), (*config.GitHubCache)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_GitHubCache_To_config_GitHubCache(a.(*GitHubCache), b.(*config.GitHubCache), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.GitHubCache)(nil), (*GitHubCache)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_GitHubCache_To_v1beta1_GitHubCache(a.(*config.GitHubCache), b.(*GitHubCache), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Ingress)(nil), (*config.Ingress)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Ingress_To_config_Ingress(a.(*Ingress), b.(*config.Ingress), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Ingress)(nil), (*Ingress)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Ingress_To_v1beta1_Ingress(a.(*config.Ingress), b.(*Ingress), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Logging)(nil), (*config.Logging)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Logging_To_config_Logging(a.(*Logging), b.(*config.Logging), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Logging)(nil), (*Logging)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Logging_To_v1beta1_Logging(a.(*config.Logging), b.(*Logging), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MinioConfiguration)(nil), (*config.MinioConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MinioConfiguration_To_config_MinioConfiguration(a.(*MinioConfiguration), b.(*config.MinioConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.MinioConfiguration)(nil), (*MinioConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_MinioConfiguration_To_v1beta1_MinioConfiguration(a.(*config.MinioConfiguration), b.(*MinioConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Observability)(nil), (*config.Observability)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Observability_To_config_Observability(a.(*Observability), b.(*config.Observability), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Observability)(nil), (*Observability)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Observability_To_v1beta1_Observability(a.(*config.Observability), b.(*Observability), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReservedExcessCapacity)(nil), (*config.ReservedExcessCapacity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ReservedExcessCapacity_To_config_ReservedExcessCapacity(a.(*ReservedExcessCapacity), b.(*config.ReservedExcessCapacity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ReservedExcessCapacity)(nil), (*ReservedExcessCapacity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ReservedExcessCapacity_To_v1beta1_ReservedExcessCapacity(a.(*config.ReservedExcessCapacity), b.(*ReservedExcessCapacity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S3)(nil), (*config.S3)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_S3_To_config_S3(a.(*S3), b.(*config.S3), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.S3)(nil), (*S3)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_S3_To_v1beta1_S3(a.(*config.S3), b.(*S3), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*S3Server)(nil), (*config.S3Server)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_S3Server_To_config_S3Server(a.(*S3Server), b.(*config.S3Server), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.S3Server)(nil), (*S3Server)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_S3Server_To_v1beta1_S3Server(a.(*config.S3Server), b.(*S3Server), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TestMachinery)(nil), (*config.TestMachinery)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TestMachinery_To_config_TestMachinery(a.(*TestMachinery), b.(*config.TestMachinery), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.TestMachinery)(nil), (*TestMachinery)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_TestMachinery_To_v1beta1_TestMachinery(a.(*config.TestMachinery), b.(*TestMachinery), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WebhookConfig)(nil), (*config.WebhookConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_WebhookConfig_To_config_WebhookConfig(a.(*WebhookConfig), b.(*config.WebhookConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.WebhookConfig)(nil), (*WebhookConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_WebhookConfig_To_v1beta1_WebhookConfig(a.(*config.WebhookConfig), b.(*WebhookConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_Argo_To_config_Argo(in *Argo, out *config.Argo, s conversion.Scope) error {
	if err := Convert_v1beta1_ArgoUI_To_config_ArgoUI(&in.ArgoUI, &out.ArgoUI, s); err != nil {
		return err
	}
	out.ChartValues = *(*json.RawMessage)(unsafe.Pointer(&in.ChartValues))
	return nil
}

// Convert_v1beta1_Argo_To_config_Argo is an autogenerated conversion function.
func Convert_v1beta1_Argo_To_config_Argo(in *Argo, out *config.Argo, s conversion.Scope) error {
	return autoConvert_v1beta1_Argo_To_config_Argo(in, out, s)
}

func autoConvert_config_Argo_To_v1beta1_Argo(in *config.Argo, out *Argo, s conversion.Scope) error {
	if err := Convert_config_ArgoUI_To_v1beta1_ArgoUI(&in.ArgoUI, &out.ArgoUI, s); err != nil {
		return err
	}
	out.ChartValues = *(*json.RawMessage)(unsafe.Pointer(&in.ChartValues))
	return nil
}

// Convert_config_Argo_To_v1beta1_Argo is an autogenerated conversion function.
func Convert_config_Argo_To_v1beta1_Argo(in *config.Argo, out *Argo, s conversion.Scope) error {
	return autoConvert_config_Argo_To_v1beta1_Argo(in, out, s)
}

func autoConvert_v1beta1_ArgoUI_To_config_ArgoUI(in *ArgoUI, out *config.ArgoUI, s conversion.Scope) error {
	if err := Convert_v1beta1_Ingress_To_config_Ingress(&in.Ingress, &out.Ingress, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_ArgoUI_To_config_ArgoUI is an autogenerated conversion function.
func Convert_v1beta1_ArgoUI_To_config_ArgoUI(in *ArgoUI, out *config.ArgoUI, s conversion.Scope) error {
	return autoConvert_v1beta1_ArgoUI_To_config_ArgoUI(in, out, s)
}

func autoConvert_config_ArgoUI_To_v1beta1_ArgoUI(in *config.ArgoUI, out *ArgoUI, s conversion.Scope) error {
	if err := Convert_config_Ingress_To_v1beta1_Ingress(&in.Ingress, &out.Ingress, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_ArgoUI_To_v1beta1_ArgoUI is an autogenerated conversion function.
func Convert_config_ArgoUI_To_v1beta1_ArgoUI(in *config.ArgoUI, out *ArgoUI, s conversion.Scope) error {
	return autoConvert_config_ArgoUI_To_v1beta1_ArgoUI(in, out, s)
}

func autoConvert_v1beta1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	if err := Convert_v1beta1_Controller_To_config_Controller(&in.Controller, &out.Controller, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_TestMachinery_To_config_TestMachinery(&in.TestMachinery, &out.TestMachinery, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_Argo_To_config_Argo(&in.Argo, &out.Argo, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_GitHub_To_config_GitHub(&in.GitHub, &out.GitHub, s); err != nil {
		return err
	}
	out.S3 = (*config.S3)(unsafe.Pointer(in.S3))
	out.ElasticSearch = (*config.ElasticSearch)(unsafe.Pointer(in.ElasticSearch))
	out.ReservedExcessCapacity = (*config.ReservedExcessCapacity)(unsafe.Pointer(in.ReservedExcessCapacity))
	if err := Convert_v1beta1_Observability_To_config_Observability(&in.Observability, &out.Observability, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Configuration_To_config_Configuration is an autogenerated conversion function.
func Convert_v1beta1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	return autoConvert_v1beta1_Configuration_To_config_Configuration(in, out, s)
}

func autoConvert_config_Configuration_To_v1beta1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	if err := Convert_config_Controller_To_v1beta1_Controller(&in.Controller, &out.Controller, s); err != nil {
		return err
	}
	if err := Convert_config_TestMachinery_To_v1beta1_TestMachinery(&in.TestMachinery, &out.TestMachinery, s); err != nil {
		return err
	}
	if err := Convert_config_Argo_To_v1beta1_Argo(&in.Argo, &out.Argo, s); err != nil {
		return err
	}
	if err := Convert_config_GitHub_To_v1beta1_GitHub(&in.GitHub, &out.GitHub, s); err != nil {
		return err
	}
	out.S3 = (*S3)(unsafe.Pointer(in.S3))
	out.ElasticSearch = (*ElasticSearch)(unsafe.Pointer(in.ElasticSearch))
	out.ReservedExcessCapacity = (*ReservedExcessCapacity)(unsafe.Pointer(in.ReservedExcessCapacity))
	if err := Convert_config_Observability_To_v1beta1_Observability(&in.Observability, &out.Observability, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_Configuration_To_v1beta1_Configuration is an autogenerated conversion function.
func Convert_config_Configuration_To_v1beta1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	return autoConvert_config_Configuration_To_v1beta1_Configuration(in, out, s)
}

func autoConvert_v1beta1_Controller_To_config_Controller(in *Controller, out *config.Controller, s conversion.Scope) error {
	out.HealthAddr = in.HealthAddr
	out.MetricsAddr = in.MetricsAddr
	out.EnableLeaderElection = in.EnableLeaderElection
	out.MaxConcurrentSyncs = in.MaxConcurrentSyncs
	if err := Convert_v1beta1_WebhookConfig_To_config_WebhookConfig(&in.WebhookConfig, &out.WebhookConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Controller_To_config_Controller is an autogenerated conversion function.
func Convert_v1beta1_Controller_To_config_Controller(in *Controller, out *config.Controller, s conversion.Scope) error {
	return autoConvert_v1beta1_Controller_To_config_Controller(in, out, s)
}

func autoConvert_config_Controller_To_v1beta1_Controller(in *config.Controller, out *Controller, s conversion.Scope) error {
	out.HealthAddr = in.HealthAddr
	out.MetricsAddr = in.MetricsAddr
	out.EnableLeaderElection = in.EnableLeaderElection
	out.MaxConcurrentSyncs = in.MaxConcurrentSyncs
	if err := Convert_config_WebhookConfig_To_v1beta1_WebhookConfig(&in.WebhookConfig, &out.WebhookConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_Controller_To_v1beta1_Controller is an autogenerated conversion function.
func Convert_config_Controller_To_v1beta1_Controller(in *config.Controller, out *Controller, s conversion.Scope) error {
	return autoConvert_config_Controller_To_v1beta1_Controller(in, out, s)
}

func autoConvert_v1beta1_ElasticSearch_To_config_ElasticSearch(in *ElasticSearch, out *config.ElasticSearch, s conversion.Scope) error {
	out.Endpoint = in.Endpoint
	out.Username = in.Username
	out.Password = in.Password
	return nil
}

// Convert_v1beta1_ElasticSearch_To_config_ElasticSearch is an autogenerated conversion function.
func Convert_v1beta1_ElasticSearch_To_config_ElasticSearch(in *ElasticSearch, out *config.ElasticSearch, s conversion.Scope) error {
	return autoConvert_v1beta1_ElasticSearch_To_config_ElasticSearch(in, out, s)
}

func autoConvert_config_ElasticSearch_To_v1beta1_ElasticSearch(in *config.ElasticSearch, out *ElasticSearch, s conversion.Scope) error {
	out.Endpoint = in.Endpoint
	out.Username = in.Username
	out.Password = in.Password
	return nil
}

// Convert_config_ElasticSearch_To_v1beta1_ElasticSearch is an autogenerated conversion function.
func Convert_config_ElasticSearch_To_v1beta1_ElasticSearch(in *config.ElasticSearch, out *ElasticSearch, s conversion.Scope) error {
	return autoConvert_config_ElasticSearch_To_v1beta1_ElasticSearch(in, out, s)
}

func autoConvert_v1beta1_GitHub_To_config_GitHub(in *GitHub, out *config.GitHub, s conversion.Scope) error {
	out.Cache = (*config.GitHubCache)(unsafe.Pointer(in.Cache))
	out.SecretsPath = in.SecretsPath
	return nil
}

// Convert_v1beta1_GitHub_To_config_GitHub is an autogenerated conversion function.
func Convert_v1beta1_GitHub_To_config_GitHub(in *GitHub, out *config.GitHub, s conversion.Scope) error {
	return autoConvert_v1beta1_GitHub_To_config_GitHub(in, out, s)
}

func autoConvert_config_GitHub_To_v1beta1_GitHub(in *config.GitHub, out *GitHub, s conversion.Scope) error {
	out.Cache = (*GitHubCache)(unsafe.Pointer(in.Cache))
	out.SecretsPath = in.SecretsPath
	return nil
}

// Convert_config_GitHub_To_v1beta1_GitHub is an autogenerated conversion function.
func Convert_config_GitHub_To_v1beta1_GitHub(in *config.GitHub, out *GitHub, s conversion.Scope) error {
	return autoConvert_config_GitHub_To_v1beta1_GitHub(in, out, s)
}

func autoConvert_v1beta1_GitHubCache_To_config_GitHubCache(in *GitHubCache, out *config.GitHubCache, s conversion.Scope) error {
	out.CacheDir = in.CacheDir
	out.CacheDiskSizeGB = in.CacheDiskSizeGB
	out.MaxAgeSeconds = in.MaxAgeSeconds
	return nil
}

// Convert_v1beta1_GitHubCache_To_config_GitHubCache is an autogenerated conversion function.
func Convert_v1beta1_GitHubCache_To_config_GitHubCache(in *GitHubCache, out *config.GitHubCache, s conversion.Scope) error {
	return autoConvert_v1beta1_GitHubCache_To_config_GitHubCache(in, out, s)
}

func autoConvert_config_GitHubCache_To_v1beta1_GitHubCache(in *config.GitHubCache, out *GitHubCache, s conversion.Scope) error {
	out.CacheDir = in.CacheDir
	out.CacheDiskSizeGB = in.CacheDiskSizeGB
	out.MaxAgeSeconds = in.MaxAgeSeconds
	return nil
}

// Convert_config_GitHubCache_To_v1beta1_GitHubCache is an autogenerated conversion function.
func Convert_config_GitHubCache_To_v1beta1_GitHubCache(in *config.GitHubCache, out *GitHubCache, s conversion.Scope) error {
	return autoConvert_config_GitHubCache_To_v1beta1_GitHubCache(in, out, s)
}

func autoConvert_v1beta1_Ingress_To_config_Ingress(in *Ingress, out *config.Ingress, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Host = in.Host
	return nil
}

// Convert_v1beta1_Ingress_To_config_Ingress is an autogenerated conversion function.
func Convert_v1beta1_Ingress_To_config_Ingress(in *Ingress, out *config.Ingress, s conversion.Scope) error {
	return autoConvert_v1beta1_Ingress_To_config_Ingress(in, out, s)
}

func autoConvert_config_Ingress_To_v1beta1_Ingress(in *config.Ingress, out *Ingress, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Host = in.Host
	return nil
}

// Convert_config_Ingress_To_v1beta1_Ingress is an autogenerated conversion function.
func Convert_config_Ingress_To_v1beta1_Ingress(in *config.Ingress, out *Ingress, s conversion.Scope) error {
	return autoConvert_config_Ingress_To_v1beta1_Ingress(in, out, s)
}

func autoConvert_v1beta1_Logging_To_config_Logging(in *Logging, out *config.Logging, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.StorageClass = in.StorageClass
	out.ChartValues = *(*json.RawMessage)(unsafe.Pointer(&in.ChartValues))
	return nil
}

// Convert_v1beta1_Logging_To_config_Logging is an autogenerated conversion function.
func Convert_v1beta1_Logging_To_config_Logging(in *Logging, out *config.Logging, s conversion.Scope) error {
	return autoConvert_v1beta1_Logging_To_config_Logging(in, out, s)
}

func autoConvert_config_Logging_To_v1beta1_Logging(in *config.Logging, out *Logging, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.StorageClass = in.StorageClass
	out.ChartValues = *(*json.RawMessage)(unsafe.Pointer(&in.ChartValues))
	return nil
}

// Convert_config_Logging_To_v1beta1_Logging is an autogenerated conversion function.
func Convert_config_Logging_To_v1beta1_Logging(in *config.Logging, out *Logging, s conversion.Scope) error {
	return autoConvert_config_Logging_To_v1beta1_Logging(in, out, s)
}

func autoConvert_v1beta1_MinioConfiguration_To_config_MinioConfiguration(in *MinioConfiguration, out *config.MinioConfiguration, s conversion.Scope) error {
	out.Distributed = in.Distributed
	if err := Convert_v1beta1_Ingress_To_config_Ingress(&in.Ingress, &out.Ingress, s); err != nil {
		return err
	}
	out.ChartValues = *(*json.RawMessage)(unsafe.Pointer(&in.ChartValues))
	return nil
}

// Convert_v1beta1_MinioConfiguration_To_config_MinioConfiguration is an autogenerated conversion function.
func Convert_v1beta1_MinioConfiguration_To_config_MinioConfiguration(in *MinioConfiguration, out *config.MinioConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta1_MinioConfiguration_To_config_MinioConfiguration(in, out, s)
}

func autoConvert_config_MinioConfiguration_To_v1beta1_MinioConfiguration(in *config.MinioConfiguration, out *MinioConfiguration, s conversion.Scope) error {
	out.Distributed = in.Distributed
	if err := Convert_config_Ingress_To_v1beta1_Ingress(&in.Ingress, &out.Ingress, s); err != nil {
		return err
	}
	out.ChartValues = *(*json.RawMessage)(unsafe.Pointer(&in.ChartValues))
	return nil
}

// Convert_config_MinioConfiguration_To_v1beta1_MinioConfiguration is an autogenerated conversion function.
func Convert_config_MinioConfiguration_To_v1beta1_MinioConfiguration(in *config.MinioConfiguration, out *MinioConfiguration, s conversion.Scope) error {
	return autoConvert_config_MinioConfiguration_To_v1beta1_MinioConfiguration(in, out, s)
}

func autoConvert_v1beta1_Observability_To_config_Observability(in *Observability, out *config.Observability, s conversion.Scope) error {
	out.Logging = (*config.Logging)(unsafe.Pointer(in.Logging))
	return nil
}

// Convert_v1beta1_Observability_To_config_Observability is an autogenerated conversion function.
func Convert_v1beta1_Observability_To_config_Observability(in *Observability, out *config.Observability, s conversion.Scope) error {
	return autoConvert_v1beta1_Observability_To_config_Observability(in, out, s)
}

func autoConvert_config_Observability_To_v1beta1_Observability(in *config.Observability, out *Observability, s conversion.Scope) error {
	out.Logging = (*Logging)(unsafe.Pointer(in.Logging))
	return nil
}

// Convert_config_Observability_To_v1beta1_Observability is an autogenerated conversion function.
func Convert_config_Observability_To_v1beta1_Observability(in *config.Observability, out *Observability, s conversion.Scope) error {
	return autoConvert_config_Observability_To_v1beta1_Observability(in, out, s)
}

func autoConvert_v1beta1_ReservedExcessCapacity_To_config_ReservedExcessCapacity(in *ReservedExcessCapacity, out *config.ReservedExcessCapacity, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Resources = (*v1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	return nil
}

// Convert_v1beta1_ReservedExcessCapacity_To_config_ReservedExcessCapacity is an autogenerated conversion function.
func Convert_v1beta1_ReservedExcessCapacity_To_config_ReservedExcessCapacity(in *ReservedExcessCapacity, out *config.ReservedExcessCapacity, s conversion.Scope) error {
	return autoConvert_v1beta1_ReservedExcessCapacity_To_config_ReservedExcessCapacity(in, out, s)
}

func autoConvert_config_ReservedExcessCapacity_To_v1beta1_ReservedExcessCapacity(in *config.ReservedExcessCapacity, out *ReservedExcessCapacity, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Resources = (*v1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	return nil
}

// Convert_config_ReservedExcessCapacity_To_v1beta1_ReservedExcessCapacity is an autogenerated conversion function.
func Convert_config_ReservedExcessCapacity_To_v1beta1_ReservedExcessCapacity(in *config.ReservedExcessCapacity, out *ReservedExcessCapacity, s conversion.Scope) error {
	return autoConvert_config_ReservedExcessCapacity_To_v1beta1_ReservedExcessCapacity(in, out, s)
}

func autoConvert_v1beta1_S3_To_config_S3(in *S3, out *config.S3, s conversion.Scope) error {
	if err := Convert_v1beta1_S3Server_To_config_S3Server(&in.Server, &out.Server, s); err != nil {
		return err
	}
	out.BucketName = in.BucketName
	out.AccessKey = in.AccessKey
	out.SecretKey = in.SecretKey
	return nil
}

// Convert_v1beta1_S3_To_config_S3 is an autogenerated conversion function.
func Convert_v1beta1_S3_To_config_S3(in *S3, out *config.S3, s conversion.Scope) error {
	return autoConvert_v1beta1_S3_To_config_S3(in, out, s)
}

func autoConvert_config_S3_To_v1beta1_S3(in *config.S3, out *S3, s conversion.Scope) error {
	if err := Convert_config_S3Server_To_v1beta1_S3Server(&in.Server, &out.Server, s); err != nil {
		return err
	}
	out.BucketName = in.BucketName
	out.AccessKey = in.AccessKey
	out.SecretKey = in.SecretKey
	return nil
}

// Convert_config_S3_To_v1beta1_S3 is an autogenerated conversion function.
func Convert_config_S3_To_v1beta1_S3(in *config.S3, out *S3, s conversion.Scope) error {
	return autoConvert_config_S3_To_v1beta1_S3(in, out, s)
}

func autoConvert_v1beta1_S3Server_To_config_S3Server(in *S3Server, out *config.S3Server, s conversion.Scope) error {
	out.Minio = (*config.MinioConfiguration)(unsafe.Pointer(in.Minio))
	out.Endpoint = in.Endpoint
	out.SSL = in.SSL
	return nil
}

// Convert_v1beta1_S3Server_To_config_S3Server is an autogenerated conversion function.
func Convert_v1beta1_S3Server_To_config_S3Server(in *S3Server, out *config.S3Server, s conversion.Scope) error {
	return autoConvert_v1beta1_S3Server_To_config_S3Server(in, out, s)
}

func autoConvert_config_S3Server_To_v1beta1_S3Server(in *config.S3Server, out *S3Server, s conversion.Scope) error {
	out.Minio = (*MinioConfiguration)(unsafe.Pointer(in.Minio))
	out.Endpoint = in.Endpoint
	out.SSL = in.SSL
	return nil
}

// Convert_config_S3Server_To_v1beta1_S3Server is an autogenerated conversion function.
func Convert_config_S3Server_To_v1beta1_S3Server(in *config.S3Server, out *S3Server, s conversion.Scope) error {
	return autoConvert_config_S3Server_To_v1beta1_S3Server(in, out, s)
}

func autoConvert_v1beta1_TestMachinery_To_config_TestMachinery(in *TestMachinery, out *config.TestMachinery, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.TestDefPath = in.TestDefPath
	out.PrepareImage = in.PrepareImage
	out.BaseImage = in.BaseImage
	out.Local = in.Local
	out.Insecure = in.Insecure
	out.DisableCollector = in.DisableCollector
	out.CleanWorkflowPods = in.CleanWorkflowPods
	return nil
}

// Convert_v1beta1_TestMachinery_To_config_TestMachinery is an autogenerated conversion function.
func Convert_v1beta1_TestMachinery_To_config_TestMachinery(in *TestMachinery, out *config.TestMachinery, s conversion.Scope) error {
	return autoConvert_v1beta1_TestMachinery_To_config_TestMachinery(in, out, s)
}

func autoConvert_config_TestMachinery_To_v1beta1_TestMachinery(in *config.TestMachinery, out *TestMachinery, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.TestDefPath = in.TestDefPath
	out.PrepareImage = in.PrepareImage
	out.BaseImage = in.BaseImage
	out.Local = in.Local
	out.Insecure = in.Insecure
	out.DisableCollector = in.DisableCollector
	out.CleanWorkflowPods = in.CleanWorkflowPods
	return nil
}

// Convert_config_TestMachinery_To_v1beta1_TestMachinery is an autogenerated conversion function.
func Convert_config_TestMachinery_To_v1beta1_TestMachinery(in *config.TestMachinery, out *TestMachinery, s conversion.Scope) error {
	return autoConvert_config_TestMachinery_To_v1beta1_TestMachinery(in, out, s)
}

func autoConvert_v1beta1_WebhookConfig_To_config_WebhookConfig(in *WebhookConfig, out *config.WebhookConfig, s conversion.Scope) error {
	out.Port = in.Port
	out.CertDir = in.CertDir
	return nil
}

// Convert_v1beta1_WebhookConfig_To_config_WebhookConfig is an autogenerated conversion function.
func Convert_v1beta1_WebhookConfig_To_config_WebhookConfig(in *WebhookConfig, out *config.WebhookConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_WebhookConfig_To_config_WebhookConfig(in, out, s)
}

func autoConvert_config_WebhookConfig_To_v1beta1_WebhookConfig(in *config.WebhookConfig, out *WebhookConfig, s conversion.Scope) error {
	out.Port = in.Port
	out.CertDir = in.CertDir
	return nil
}

// Convert_config_WebhookConfig_To_v1beta1_WebhookConfig is an autogenerated conversion function.
func Convert_config_WebhookConfig_To_v1beta1_WebhookConfig(in *config.WebhookConfig, out *WebhookConfig, s conversion.Scope) error {
	return autoConvert_config_WebhookConfig_To_v1beta1_WebhookConfig(in, out, s)
}
