//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by defaulter-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&BotConfiguration{}, func(obj interface{}) { SetObjectDefaults_BotConfiguration(obj.(*BotConfiguration)) })
	scheme.AddTypeDefaultingFunc(&Configuration{}, func(obj interface{}) { SetObjectDefaults_Configuration(obj.(*Configuration)) })
	return nil
}

func SetObjectDefaults_BotConfiguration(in *BotConfiguration) {
	SetDefaults_Webserver(&in.Webserver)
	SetDefaults_Dashboard(&in.Dashboard)
	if in.Dashboard.Authentication.GitHub != nil {
		SetDefaults_GitHubAuthentication(in.Dashboard.Authentication.GitHub)
	}
	SetDefaults_GitHubBot(&in.GitHubBot)
}

func SetObjectDefaults_Configuration(in *Configuration) {
	SetDefaults_Configuration(in)
}
