// +build !ignore_autogenerated

/*
Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	json "encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoConfiguration) DeepCopyInto(out *ArgoConfiguration) {
	*out = *in
	out.ArgoUI = in.ArgoUI
	if in.ChartValues != nil {
		in, out := &in.ChartValues, &out.ChartValues
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoConfiguration.
func (in *ArgoConfiguration) DeepCopy() *ArgoConfiguration {
	if in == nil {
		return nil
	}
	out := new(ArgoConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoUIConfiguration) DeepCopyInto(out *ArgoUIConfiguration) {
	*out = *in
	out.Ingress = in.Ingress
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoUIConfiguration.
func (in *ArgoUIConfiguration) DeepCopy() *ArgoUIConfiguration {
	if in == nil {
		return nil
	}
	out := new(ArgoUIConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Configuration) DeepCopyInto(out *Configuration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ControllerConfig = in.ControllerConfig
	out.TestMachineryConfiguration = in.TestMachineryConfiguration
	in.GitHub.DeepCopyInto(&out.GitHub)
	if in.S3Configuration != nil {
		in, out := &in.S3Configuration, &out.S3Configuration
		*out = new(S3Configuration)
		(*in).DeepCopyInto(*out)
	}
	if in.ElasticSearchConfiguration != nil {
		in, out := &in.ElasticSearchConfiguration, &out.ElasticSearchConfiguration
		*out = new(ElasticSearchConfiguration)
		**out = **in
	}
	in.Argo.DeepCopyInto(&out.Argo)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Configuration.
func (in *Configuration) DeepCopy() *Configuration {
	if in == nil {
		return nil
	}
	out := new(Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Configuration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfig) DeepCopyInto(out *ControllerConfig) {
	*out = *in
	out.WebhookConfig = in.WebhookConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfig.
func (in *ControllerConfig) DeepCopy() *ControllerConfig {
	if in == nil {
		return nil
	}
	out := new(ControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticSearchConfiguration) DeepCopyInto(out *ElasticSearchConfiguration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticSearchConfiguration.
func (in *ElasticSearchConfiguration) DeepCopy() *ElasticSearchConfiguration {
	if in == nil {
		return nil
	}
	out := new(ElasticSearchConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubCacheConfig) DeepCopyInto(out *GitHubCacheConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubCacheConfig.
func (in *GitHubCacheConfig) DeepCopy() *GitHubCacheConfig {
	if in == nil {
		return nil
	}
	out := new(GitHubCacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubConfig) DeepCopyInto(out *GitHubConfig) {
	*out = *in
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(GitHubCacheConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubConfig.
func (in *GitHubConfig) DeepCopy() *GitHubConfig {
	if in == nil {
		return nil
	}
	out := new(GitHubConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressConfiguration) DeepCopyInto(out *IngressConfiguration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressConfiguration.
func (in *IngressConfiguration) DeepCopy() *IngressConfiguration {
	if in == nil {
		return nil
	}
	out := new(IngressConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioConfiguration) DeepCopyInto(out *MinioConfiguration) {
	*out = *in
	out.Ingress = in.Ingress
	if in.ChartValues != nil {
		in, out := &in.ChartValues, &out.ChartValues
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioConfiguration.
func (in *MinioConfiguration) DeepCopy() *MinioConfiguration {
	if in == nil {
		return nil
	}
	out := new(MinioConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Configuration) DeepCopyInto(out *S3Configuration) {
	*out = *in
	in.Server.DeepCopyInto(&out.Server)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Configuration.
func (in *S3Configuration) DeepCopy() *S3Configuration {
	if in == nil {
		return nil
	}
	out := new(S3Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3ServerConfiguration) DeepCopyInto(out *S3ServerConfiguration) {
	*out = *in
	if in.Minio != nil {
		in, out := &in.Minio, &out.Minio
		*out = new(MinioConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3ServerConfiguration.
func (in *S3ServerConfiguration) DeepCopy() *S3ServerConfiguration {
	if in == nil {
		return nil
	}
	out := new(S3ServerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestMachineryConfiguration) DeepCopyInto(out *TestMachineryConfiguration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestMachineryConfiguration.
func (in *TestMachineryConfiguration) DeepCopy() *TestMachineryConfiguration {
	if in == nil {
		return nil
	}
	out := new(TestMachineryConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookConfig) DeepCopyInto(out *WebhookConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookConfig.
func (in *WebhookConfig) DeepCopy() *WebhookConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookConfig)
	in.DeepCopyInto(out)
	return out
}
