
---
{{ if .Values.argoui.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    annotations:
        {{- range $key, $value := .Values.argoui.ingress.annotations }}
        {{ $key }}: {{ $value }}
        {{- end }}
    labels:
        garden.sapcloud.io/purpose: managed-cert
        {{- range $key, $value := .Values.argoui.ingress.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    name: {{ .Values.argoui.ingress.name }}
    namespace: {{ .Release.Namespace }}
spec:
    rules:
    - host: {{ .Values.argoui.ingress.host }}
      http:
          paths:
          - backend:
                serviceName: argo-ui
                servicePort: 80
            path: /
    tls:
    - hosts:
      - {{ .Values.argoui.ingress.host }}
      secretName: argo-ui-tls
{{ end }}