---
{{- if .Values.global.loggingEnabled }}
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "loki.fullname" . }}
  namespace: {{ .Values.global.loggingNamespace }}
  labels:
    app: {{ template "loki.name" . }}
    chart: {{ template "loki.chart" . }}
    release: {{ template "logging.releaseName" . }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      name: {{ template "loki.fullname" . }}
      app: {{ template "loki.name" . }}
      release: {{ template "logging.releaseName" . }}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ template "client.name" . }}
            release: {{ template "logging.releaseName" . }}
    - ports:
      - port: {{ .Values.service.port }}
{{- end -}}
{{- end -}}
