---
{{- if .Values.global.loggingEnabled }}
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "loki.fullname" . }}
  namespace: {{ .Values.global.loggingNamespace }}
  labels:
    app: {{ template "loki.name" . }}
    chart: {{ template "loki.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ template "logging.releaseName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "loki.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "loki.serviceAccountName" . }}
{{- end }}
{{- end }}

