---
{{- if .Values.global.loggingEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "loki.fullname" . }}-headless
  namespace: {{ .Values.global.loggingNamespace }}
  labels:
    app: {{ template "loki.name" . }}
    chart: {{ template "loki.chart" . }}
    release: {{ template "logging.releaseName" . }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
{{- if .Values.extraPorts }}
{{ toYaml .Values.extraPorts | indent 4}}
{{- end }}
  selector:
    app: {{ template "loki.name" . }}
    release: {{ template "logging.releaseName" . }}
{{- end }}