# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# TestRun CRDs will be created by Test-Machinery controllers, by concourse jobs or manually to run e.g. single tests.
apiVersion: testmachinery.sapcloud.io/v1beta1
kind: Testrun
metadata:
  generateName: integration-
  namespace: default
spec:
  owner: gardener@example.com # test owner and contact person in case of a test failure
  recipientsOnFailure: developer1@example.com, developer2@example.com # optional, list of emails to be notified if a step fails

  # defines where to look for TestDefs
  locationSets:
  - name: github-locations
    # optional; defines the default location set which is used if no specific location is defined for a step.
    default: true
    locations:
      - type: git
        repo: https://github.com/gardener/gardener.git
        revision: master
      - type: git
        repo: https://github.com/gardener/test-infra.git
        revision: master

  kubeconfigs:
    gardener: #base64 heredoc kubeconfig
    seed:
      secretKeyRef:
        name: mysecret
        key: kubeconfig
    shoot:


  # Global config available to every test task in all phases (testFlow and onExit)
  config:
    - name: SHOOTNAME
      value: "integration-abc12"
      type: env

  # the execution flow:
  testflow:
    - name: create-step
      definition:
        name: create-shoot
    - name: delete-step
      dependsOn: [ create-step ]
      definition:
        name: delete-shoot
#    - name: label-step
#      dependsOn: [ demo-step ]
#      definition:
#        label: default

#  onExit:
#    - - name: delete-shoot
#        condition: error
