# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# TestRun CRDs will be created by Test-Machinery controllers, by concourse jobs or manually to run e.g. single tests.
apiVersion: testmachinery.sapcloud.io/v1beta1
kind: Testrun
metadata:
  generateName: integration-
  namespace: default
spec:
  creator: pipeline-xyz # for diagnostic purposes, could contain the concourse job url as well

  # defines where to look for TestDefs
  locationSets:
    - name: local-locations
      # optional; defines the default location set which is used if no specific location is defined for a step.
      default: true
      locations:
      - type: local
        hostPath: /tmp/tm # local disk path musst be mounted to minikube volume at "/tmp/tm"

  kubeconfigs:
    gardener: #base64 heredoc kubeconfig
    seed:
    shoot:


  # Global config available to every test task in all phases (testFlow and onExit)
  config:
    - name: SHOOTNAME
      value: "integration-abc12"
      type: env

  # the execution flow:
  testflow:
  - name: demo-step
    definition:
      name: demo
  - name: label-step
    dependsOn: [ demo-step ]
    definition:
      label: default

  onExit:
  - name: exit
    definition:
      name: exit-handler
