# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# TestRun CRDs will be created by Test-Machinery controllers, by CI/CD jobs or manually to run e.g. single tests.
apiVersion: testmachinery.sapcloud.io/v1beta1
kind: Testrun
metadata:
  generateName: dummy-
  namespace: default
spec:
  owner: gardener@example.com # test owner and contact person in case of a test failure

  # defines where to look for TestDefs
  locationSets:
  - name: github-locations
    # optional; defines the default location set which is used if no specific location is defined for a step.
    default: true
    locations:
      - type: git
        repo: https://github.com/gardener/test-infra.git
        revision: master

  # Global config available to every test task in all phases (testFlow and onExit)
  config:
    - name: DURATION
      value: "5"
      type: env

  # the execution flow:
  testflow:
    - name: dummy
      definition:
        name: dummy
