# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# Testrun CRs will be created by Testmachinery controllers, by concourse jobs or manually to run e.g. single tests.
apiVersion: testmachinery.sapcloud.io/v1beta1
kind: Testrun
metadata:
  generateName: integration-
  namespace: default
spec:

  locationSets:
  - name: default
    default: true
    locations:
    - type: git
      repo: https://github.com/gardener/gardener.git
      revision: master
    - type: git
      repo: https://github.com/your/git/repo.git
      revision: master

  kubeconfigs:
    gardener: #base64 heredoc kubeconfig

  config:
  - name: PROJECT_NAMESPACE
      type: env
      value: garden-core
    - name: SHOOT_NAME
      type: env
      value: my-shoot-name
    - name: CLOUDPROVIDER
      type: env
      value: gcp
    - name: K8S_VERSION
      type: env
      value: 1.14.3

  # the execution flow:
  testflow:
  - name: create-shoot
    definition:
      name: create-shoot
      config: # for more options see https://github.com/gardener/gardener/blob/master/.test-defs/cmd/create-shoot/main.go
      - name: CLOUDPROFILE
        type: env
        value: gcp
      - name: SECRET_BINDING
        type: env
        value: core-gcp-gcp
      - name: REGION
        type: env
        value: europe-west1
      - name: ZONE
        type: env
        value: europe-west1-a

  - name: test
    dependsOn: [ create-shoot ]
    definition:
      name: your-testdef-name

  - name: delete-shoot
    dependsOn: [ tests ]
    definition:
      name: delete-shoot

  onExit:
  - name: delete-shoot
    definition:
      name: delete-shoot
      condition: error
