# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# Testrun CRs will be created by Testmachinery controllers, by CI/CD jobs or manually to run e.g. single tests.
apiVersion: testmachinery.sapcloud.io/v1beta1
kind: Testrun
metadata:
  generateName: integration-
  namespace: default
spec:

  locationSets:
  - name: default
    default: true
    locations:
    - type: git
      repo: https://github.com/your/git/repo.git
      revision: master

  kubeconfigs:
    gardener: #base64 heredoc kubeconfig
    seed:
    shoot:

  testflow:
  - name: test
    definition:
      name: your-testdef-name
