---
{{- if .Values.global.loggingEnabled }}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "promtail.name" . }}
    chart: {{ template "promtail.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ template "logging.releaseName" . }}
  name: {{ template "promtail.serviceAccountName" . }}
  namespace: {{ .Values.global.loggingNamespace }}
{{- end }}
{{- end }}

