---
{{- if .Values.global.loggingEnabled }}
{{- if .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "promtail.fullname" . }}-headless
  namespace: {{ .Values.global.loggingNamespace }}
  labels:
    app: {{ template "promtail.name" . }}
    chart: {{ template "promtail.chart" . }}
    release: {{ template "logging.releaseName" . }}
    heritage: {{ template "logging.releaseName" . }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app: {{ template "promtail.name" . }}
    release: {{ template "logging.releaseName" . }}
{{- end }}
{{- end }}
