# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

{{- if semverCompare ">= 1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: tm-bot
  namespace: {{ .Release.Namespace }}
  labels:
    garden.sapcloud.io/purpose: managed-cert
    {{- range $key, $value := .Values.ingress.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: tm-bot-ingress-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      {{- if semverCompare ">= 1.19-0" .Capabilities.KubeVersion.GitVersion }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tm-bot
            port:
              number: 80
      {{- else }}
      - path: /
        backend:
          serviceName: tm-bot
          servicePort: 80
      {{- end }}
