# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Secret
metadata:
  name: tm-bot-configuration
  namespace: {{ .Release.Namespace }}
  labels:
    app: testmachinery-controller
type: Opaque
data:
  config.yaml: {{ include "config" . | b64enc | trim }}