# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: tm-bot-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app: tm-bot
type: Opaque
data:
  tls.crt: {{ required ".Values.bot.tls.crt is required" (b64enc .Values.bot.tls.crt) }}
  tls.key: {{ required ".Values.bot.tls.key is required" (b64enc .Values.bot.tls.key) }}