# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.githubAppPrivateKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tm-bot-github
  namespace: {{ .Release.Namespace }}
  labels:
    app: testmachinery-controller
type: Opaque
data:
  key: {{ .Values.githubAppPrivateKey | b64enc | trim }}
{{ end }}