# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required ".Values.bot.serviceAccountName is required" .Values.bot.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: tm-bot