# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: tm-bot
  namespace: {{ .Release.Namespace }}
  labels:
    app: tm-bot
spec:
  selector:
    app: tm-bot
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: {{.Values.configuration.webserver.httpPort}}
  - name: https
    protocol: TCP
    port: 443
    targetPort: {{.Values.configuration.webserver.httpsPort}}
