#!/bin/bash -e
#
# Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FILEPATH="$1"

for repo in $(cat "$FILEPATH" | jq -c '.[]' ); do
    url=$( echo $repo | jq -r '.url')
    revision=$( echo $repo | jq -r '.revision')
    name=$( echo $repo | jq -r '.name')

    echo "Clone repo $url with revision $revision to $TM_REPO_PATH/$name \n"
    git -c http.sslVerify=false clone -v $url $TM_REPO_PATH/$name;

    pushd .
    cd $TM_REPO_PATH/$name
    git fetch origin $revision
    git checkout $revision
    popd
done
