# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

ingress:
  host: tm-bot.example.com
  labels: {}

bot:
  image: europe-docker.pkg.dev/gardener-project/releases/testmachinery/bot
  tag: latest
  pullPolicy: IfNotPresent
  imagePullSecretName: ""
  verbosity: 2

  serviceAccountName: tm-bot

  tls:
    caBundle: |
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    crt: |
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY-----

githubAppPrivateKey: ""

configuration:
  webserver:
    httpPort: 80
    httpsPort: 443
    certificate:
      cert: /etc/tm-bot/srv/tls.crt
      privateKey: /etc/tm-bot/srv/tls.key

  githubBot:
    enabled: true
    #  configurationFilePath: ".ci/tm-config.yaml"
    defaultTeam: core
    #  apiUrl: "https://api.github.com"
    appId: 123
    appPrivateKeyPath: /etc/tm-bot/gh/key
    webhookSecret: "testing"

  dashboard:
    UIBasePath: "/app"
    authentication:
      provider: github # | dummy | noauth
      cookieSecret: sdfasdf

      githubConfig:
        organization: gardener
        oAuth:
          clientId: ""
          clientSecret: ""
          redirectUrl: "http://test.example.local/oauth/redirect"
    cache:
      cacheDir: /cache
#      cacheDiskSizeGB: 5
#      maxAgeSeconds: 60