# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
{{- if .Values.enabled }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: tm-reserve-excess-capacity
value: -5
globalDefault: false
description: "This class is used to reserve excess resource capacity on the testmachinery cluster"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reserve-excess-capacity
  namespace: {{ .Release.Namespace }}
  labels:
    app: reserve-excess-capacity
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: reserve-excess-capacity
  template:
    metadata:
      labels:
        app: reserve-excess-capacity
    spec:
      # ensure pods are placed on "purpose: testload" labeled nodes (if present)
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: purpose
                operator: In
                values:
                - testload
      tolerations:
      - key: purpose
        operator: Equal
        value: testload
        effect: NoSchedule
      terminationGracePeriodSeconds: 5
      containers:
      - name: pause-container
        image: {{ index .Values.images "reserve-excess-capacity" }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
      priorityClassName: tm-reserve-excess-capacity
{{- end }}