#! /bin/bash
#
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

echo "Starting TestMachinery Setup"
BASEPATH=$(realpath ${TM_KUBECONFIG_PATH}/..)
echo "Contents of '${BASEPATH}':"
ls -alR ${BASEPATH}

REPO_PATH=$1
REPO=$2

mkdir -p $GOPATH/src/$REPO_PATH
ln -s $(pwd) $GOPATH/src/$REPO_PATH/$REPO