loki:
  image:
    repository: grafana/loki
    tag: v1.3.0
  podAnnotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
  persistence:
    enabled: true
    storageClassName: default
  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 336h # two weeks (but probably when table gets deleted we have max 7 days of history, see https://github.com/grafana/loki/issues/916)
  resources:
    requests:
      cpu: "1"
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 4Gi
  terminationGracePeriodSeconds: 300

promtail:
  image:
    repository: grafana/promtail
    tag: v1.3.0
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  tolerations:
  - key: purpose
    operator: Equal
    value: testload
    effect: NoSchedule
  scrapeConfigs:
  - entry_parser: docker
    job_name: pods
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    # keep pod name as label (use prometheus standard name "instance" to correlate later with monitoring)
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_name
      target_label: instance
    # keep container name as label
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_container_name
      target_label: container
    # keep node (VM) label with same name as dashboards based on prometheus
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_node_name
      target_label: node
    # point promtail to correct log filenames
    - replacement: /var/log/pods/*$1/*.log
      separator: /
      source_labels:
      - __meta_kubernetes_pod_uid
      - __meta_kubernetes_pod_container_name
      target_label: __path__
    # give an argo workflow a friendly grafana label name
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_label_workflows_argoproj_io_workflow
      target_label: argo_workflow
    # give an argo workflow node/step a friendly grafana label name
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_annotation_workflows_argoproj_io_node_name
      target_label: argo_node
    # give a TM teststep a friendly grafana label name
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_annotation_testmachinery_sapcloud_io_TestDefinition
      target_label: tm_testdef
